#!/usr/bin/env python3
"""Compose global agent-context files from machine- and harness-scoped sources.

agent-compose normally synthesizes one canonical context file
(`~/.config/agent-compose/COMPOSED.md`) and points each harness's global load
point at it by symlink. Sources may optionally declare `harnesses` in YAML
frontmatter. When configured harnesses select different source slices, the
composer writes `COMPOSED.<harness>.md` files instead. Shared sources remain
shared by default, and byte-identical slices still use one file.

Sources are either listed explicitly or discovered by walking declared roots
for files named AGENTS.COMPOSE.md (forgejo #136). AGENTS.COMPOSE.md is the
disjoint source convention: it holds always-global doctrine and is never loaded
by a harness's own AGENTS.md/CLAUDE.md cascade, so composing it in does not
double-load.

Scope filtering (#137) selects which sources compose on this machine. The
machine declares `scopes`; each source declares its own `scopes` in YAML
frontmatter; a source composes iff the two sets intersect. Filtering is itself
opt-in: a config with no `scopes` key composes every source. Activation overall
is opt-in too: with no config file present the composer is a total no-op, so
every harness behaves exactly as it does without agent-compose installed.

Source frontmatter (stripped from composed output, never leaks into context):

    ---
    scopes: [kai-public, work]
    harnesses: [claude, codex]
    ---
    # always-global doctrine ...

Config schema (YAML):

    # Presence of this file activates agent-compose. Absent => no-op.
    # This machine's scope tags. Omit to compose every source (filtering off).
    scopes: [kai-public, work]
    # Explicit sources are composed first, in listed order.
    sources:
      - ~/projects/foo/AGENTS.COMPOSE.md
    # Roots are walked for AGENTS.COMPOSE.md files, appended in sorted order.
    roots:
      - ~/projects/coilysiren
      - ~/projects/coilyco-flight-deck
    # Optional load-point overrides. Defaults shown; openclaw unset => skipped.
    load_points:
      claude: ~/.claude/CLAUDE.md
      codex: ~/.codex/AGENTS.md
      openclaw:

Usage:
    agent-compose            # compose + (re)point symlinks
    agent-compose --dry-run  # print what would happen, touch nothing
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "agent-compose"
CONFIG_PATH = CONFIG_DIR / "agent-compose.yaml"
COMPOSED_PATH = CONFIG_DIR / "COMPOSED.md"

# Built-in global load points. OpenClaw has no global load point yet (forgejo
# #135 decision: defer), so it is symlinked only when set in config.
DEFAULT_LOAD_POINTS = {
    "claude": HOME / ".claude" / "CLAUDE.md",
    "codex": HOME / ".codex" / "AGENTS.md",
}

BANNER = "<!-- generated by agent-compose from agent-compose.yaml; do not edit -->"

# Disjoint source filename: always-global doctrine, never loaded by a harness's
# own AGENTS.md/CLAUDE.md cascade, only pulled in here.
SOURCE_FILENAME = "AGENTS.COMPOSE.md"


def _expand(path: str | Path) -> Path:
    return Path(path).expanduser()


def _normalize_scopes(value: object) -> list[str] | None:
    """Coerce a scopes value to a list of strings, or None when unset."""
    if value is None:
        return None
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [str(v) for v in value]
    return None


def _split_frontmatter(text: str) -> tuple[dict, str]:
    """Split a leading `--- ... ---` YAML frontmatter block from the body.

    Returns ({}, text) when there is no well-formed frontmatter fence.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            import yaml

            try:
                meta = yaml.safe_load("\n".join(lines[1:i])) or {}
            except yaml.YAMLError:
                meta = {}
            body = "\n".join(lines[i + 1 :])
            return (meta if isinstance(meta, dict) else {}), body
    return {}, text


def parse_source(path: Path) -> tuple[list[str] | None, str]:
    """Read a source: return its declared scopes and its frontmatter-stripped body.

    The scopes directive lives in YAML frontmatter and is removed from the body
    so it never reaches COMPOSED.md. Scopes are None when none are declared.
    """
    meta, body = _split_frontmatter(path.read_text(encoding="utf-8"))
    return _normalize_scopes(meta.get("scopes")), body


def source_harnesses(path: Path) -> list[str] | None:
    """Return a source's harness allowlist, or None when it applies to all."""
    meta, _ = _split_frontmatter(path.read_text(encoding="utf-8"))
    return _normalize_scopes(meta.get("harnesses"))


def select_by_scope(sources: list[Path], machine_scopes: list[str] | None) -> list[Path]:
    """Keep sources whose declared scopes intersect the machine scopes.

    machine_scopes None (no `scopes` in config) turns filtering off: every
    source is kept. Under active filtering a source with no declared scopes is
    dropped, so an untagged file never leaks onto a scoped machine.
    """
    if machine_scopes is None:
        return list(sources)
    wanted = set(machine_scopes)
    return [
        path
        for path in sources
        if (scopes := parse_source(path)[0]) and wanted.intersection(scopes)
    ]


def select_by_harness(sources: list[Path], harness: str) -> list[Path]:
    """Keep sources shared globally or explicitly enabled for harness."""
    return [
        path
        for path in sources
        if (allowed := source_harnesses(path)) is None or harness in allowed
    ]


def harness_output_path(composed_path: Path, harness: str) -> Path:
    """Return the divergent output path for a harness beside composed_path."""
    return composed_path.with_name(
        f"{composed_path.stem}.{harness}{composed_path.suffix}"
    )


def plan_outputs(
    sources: list[Path], load_points: dict[str, Path], composed_path: Path
) -> tuple[dict[str, list[Path]], dict[str, Path], list[str]]:
    """Select each harness slice and assign shared or divergent output paths."""
    slices = {
        harness: select_by_harness(sources, harness) for harness in load_points
    }
    errors = [
        f"no sources matched harness {harness!r}"
        for harness, selected in slices.items()
        if not selected
    ]
    signatures = {tuple(selected) for selected in slices.values()}
    if len(signatures) <= 1:
        outputs = {harness: composed_path for harness in load_points}
    else:
        outputs = {
            harness: harness_output_path(composed_path, harness)
            for harness in load_points
        }
    return slices, outputs, errors


def stale_generated_outputs(
    composed_path: Path, active_outputs: set[Path]
) -> list[Path]:
    """Find obsolete composer-owned outputs beside composed_path.

    Only files carrying the generated banner qualify, so similarly named user
    files are never removed.
    """
    candidates = [composed_path]
    candidates.extend(
        composed_path.parent.glob(
            f"{composed_path.stem}.*{composed_path.suffix}"
        )
    )
    stale: list[Path] = []
    for path in candidates:
        if path in active_outputs or not path.is_file():
            continue
        try:
            with path.open(encoding="utf-8") as source:
                first_line = source.readline().rstrip("\n")
        except OSError:
            continue
        if first_line == BANNER:
            stale.append(path)
    return sorted(set(stale), key=str)


def discover_sources(root: Path) -> list[Path]:
    """Find AGENTS.COMPOSE.md files under root, sorted for deterministic output.

    Dot-directories (.git, vendored caches) are skipped so discovery never pulls
    in a stray copy from version-control or dependency trees.
    """
    found = [
        path
        for path in root.rglob(SOURCE_FILENAME)
        if not any(part.startswith(".") for part in path.relative_to(root).parts)
    ]
    return sorted(found, key=lambda p: str(p))


def gather_sources(config: dict) -> tuple[list[Path], list[str]]:
    """Resolve the full source list: explicit entries first, then discovered.

    Explicit `sources` keep their listed order; each declared `root` is walked
    and its AGENTS.COMPOSE.md files appended in sorted order. Duplicates (a file
    both listed and discovered) collapse to their first occurrence. Returns the
    sources and a list of error strings (missing files, non-directory roots).
    """
    errors: list[str] = []
    ordered: list[Path] = []
    seen: set[Path] = set()

    def add(path: Path) -> None:
        key = path.resolve()
        if key not in seen:
            seen.add(key)
            ordered.append(path)

    for raw in config.get("sources") or []:
        src = _expand(raw)
        if not src.is_file():
            errors.append(f"source not found: {src}")
            continue
        add(src)

    for raw in config.get("roots") or []:
        root = _expand(raw)
        if not root.is_dir():
            errors.append(f"root is not a directory: {root}")
            continue
        for src in discover_sources(root):
            add(src)

    return ordered, errors


def compose(sources: list[Path]) -> str:
    """Concatenate source files into the composed-context body.

    Deterministic (no timestamps) so the drift check (#140) can reproduce it.
    Each section is fenced by a source-path comment for debuggability.
    """
    parts = [BANNER]
    for src in sources:
        body = parse_source(src)[1].strip("\n")
        parts.append(f"<!-- source: {src} -->\n{body}")
    return "\n\n".join(parts) + "\n"


def install_symlink(dst: Path, target: Path) -> str:
    """Point dst at target, backing up a pre-existing real file to dst.bak.

    Mirrors setup.sh's ensure_link: an existing symlink is replaced, an existing
    regular file is moved aside, parents are created. Returns a log line.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    note = ""
    if dst.is_symlink():
        dst.unlink()
    elif dst.exists():
        backup = dst.with_name(dst.name + ".bak")
        dst.replace(backup)
        note = f" (backed up prior file to {backup})"
    dst.symlink_to(target)
    return f"linked  {dst} -> {target}{note}"


def load_config(config_path: Path) -> dict:
    """Parse the YAML config. Raises RuntimeError if PyYAML is unavailable."""
    try:
        import yaml
    except ModuleNotFoundError as exc:  # pragma: no cover - env-dependent
        raise RuntimeError("PyYAML not available") from exc
    data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{config_path}: top-level YAML must be a mapping")
    return data


def resolve_load_points(config: dict) -> dict[str, Path]:
    """Merge configured load-point overrides over the built-in defaults.

    A truthy value sets (or adds) a harness's load point. An explicit falsy
    value (`null` / `false`) opts a harness out, including a default one - so a
    Claude-only machine sets `codex: null` and a Codex-only machine sets
    `claude: null`. OpenClaw stays opt-in: it is wired only when given a path.
    """
    points = dict(DEFAULT_LOAD_POINTS)
    overrides = config.get("load_points") or {}
    if isinstance(overrides, dict):
        for harness, value in overrides.items():
            if value:
                points[harness] = _expand(value)
            else:
                points.pop(harness, None)
    return points


def run(config_path: Path, composed_path: Path, *, dry_run: bool = False) -> int:
    """Compose and wire symlinks. No-op (return 0) when config is absent."""
    if not config_path.is_file():
        print(f"agent-compose: no config at {config_path}; nothing to do (opt-in)")
        return 0

    config = load_config(config_path)
    gathered, errors = gather_sources(config)
    if errors:
        for err in errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1

    machine_scopes = _normalize_scopes(config.get("scopes"))
    sources = select_by_scope(gathered, machine_scopes)
    excluded = len(gathered) - len(sources)
    if not sources:
        reason = (
            f"no sources matched this machine's scopes {machine_scopes}"
            if machine_scopes is not None
            else "no sources resolved (check `sources` / `roots`)"
        )
        sys.stderr.write(
            f"agent-compose: config present but {reason}; "
            "refusing to write an empty COMPOSED.md\n"
        )
        return 1

    load_points = resolve_load_points(config)
    slices, outputs, harness_errors = plan_outputs(
        sources, load_points, composed_path
    )
    if harness_errors:
        for err in harness_errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1
    tail = f" ({excluded} excluded by scope)" if excluded else ""

    planned: dict[Path, list[Path]] = {}
    for harness, target in outputs.items():
        planned[target] = slices[harness]
    if not load_points:
        planned[composed_path] = sources
    stale = stale_generated_outputs(composed_path, set(planned))

    if dry_run:
        for target, selected in sorted(planned.items(), key=lambda item: str(item[0])):
            print(f"would write {target} ({len(selected)} source(s)){tail}")
        for target in stale:
            print(f"would remove {target} (obsolete generated output)")
        for harness, dst in sorted(load_points.items()):
            print(f"would link  {dst} -> {outputs[harness]}  [{harness}]")
        return 0

    composed_path.parent.mkdir(parents=True, exist_ok=True)
    for target in stale:
        target.unlink()
        print(f"removed {target} (obsolete generated output)")
    for target, selected in sorted(planned.items(), key=lambda item: str(item[0])):
        target.write_text(compose(selected), encoding="utf-8")
        print(f"wrote   {target} ({len(selected)} source(s)){tail}")
    for harness, dst in sorted(load_points.items()):
        print(install_symlink(dst, outputs[harness]) + f"  [{harness}]")
    return 0


def check(config_path: Path, composed_path: Path) -> int:
    """Verify composed_path matches a fresh compose. Exit 1 on drift (#140).

    No-op (return 0) when no config is present, mirroring run()'s opt-in. On
    drift, prints a unified diff so the staleness is legible, then fails.
    """
    if not config_path.is_file():
        print(f"agent-compose: no config at {config_path}; nothing to check (opt-in)")
        return 0

    config = load_config(config_path)
    gathered, errors = gather_sources(config)
    if errors:
        for err in errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1
    sources = select_by_scope(gathered, _normalize_scopes(config.get("scopes")))
    if not sources:
        sys.stderr.write("agent-compose: no sources resolved; cannot check drift\n")
        return 1

    load_points = resolve_load_points(config)
    slices, outputs, harness_errors = plan_outputs(
        sources, load_points, composed_path
    )
    if harness_errors:
        for err in harness_errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1

    planned: dict[Path, list[Path]] = {}
    for harness, target in outputs.items():
        planned[target] = slices[harness]
    if not load_points:
        planned[composed_path] = sources
    stale = stale_generated_outputs(composed_path, set(planned))

    import difflib

    drifted = False
    for target in stale:
        drifted = True
        sys.stderr.write(
            f"agent-compose: drift - obsolete generated output remains at {target}. "
            "Run `agent-compose` to remove it.\n"
        )
    for target, selected in sorted(planned.items(), key=lambda item: str(item[0])):
        expected = compose(selected)
        actual = target.read_text(encoding="utf-8") if target.exists() else ""
        if actual == expected:
            print(f"agent-compose: {target} in sync")
            continue
        drifted = True
        sys.stderr.write(
            f"agent-compose: drift - {target} is missing, stale, or hand-edited. "
            "Run `agent-compose` to regenerate.\n"
        )
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"{target} (on disk)",
            tofile="expected (fresh compose)",
            lineterm="",
        )
        for line in list(diff)[:40]:
            sys.stderr.write(line + "\n")
    return 1 if drifted else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--dry-run", action="store_true", help="print the plan, change nothing"
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="verify COMPOSED.md is in sync with the sources; exit 1 on drift",
    )
    args = parser.parse_args()
    try:
        if args.check:
            return check(CONFIG_PATH, COMPOSED_PATH)
        return run(CONFIG_PATH, COMPOSED_PATH, dry_run=args.dry_run)
    except RuntimeError as exc:
        sys.stderr.write(f"agent-compose: {exc}\n")
        return 1


def check_main() -> int:
    """Console entry for the drift pre-commit hook (check-agent-compose-drift)."""
    try:
        return check(CONFIG_PATH, COMPOSED_PATH)
    except RuntimeError as exc:
        sys.stderr.write(f"agent-compose: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
