#!/usr/bin/env python3
"""Compose one global agent-context file from scoped sources, shared by symlink.

agent-compose synthesizes a single canonical context file
(`~/.config/agent-compose/composed.md`) from a set of source files declared in
`~/.config/agent-compose/agent-compose.yaml`, then points each harness's global
load point at that one file by symlink. Claude Code, Codex, and OpenClaw then
load byte-identical context with no duplicated content on disk.

This module is the spine (forgejo #135): an explicit source-file list, no
discovery (#136) and no scope filtering (#137) yet. Activation is opt-in: with
no config file present the composer is a total no-op, so every harness behaves
exactly as it does without agent-compose installed.

Config schema (YAML):

    # Presence of this file activates agent-compose. Absent => no-op.
    sources:
      - ~/projects/foo/AGENTS.COMPOSE.md
      - ~/projects/bar/AGENTS.COMPOSE.md
    # Optional load-point overrides. Defaults shown; openclaw unset => skipped.
    load_points:
      claude: ~/.claude/CLAUDE.md
      codex: ~/.codex/AGENTS.md
      openclaw:

Usage:
    agent-compose            # compose + (re)point symlinks
    agent-compose --dry-run  # print what would happen, touch nothing
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "agent-compose"
CONFIG_PATH = CONFIG_DIR / "agent-compose.yaml"
COMPOSED_PATH = CONFIG_DIR / "composed.md"

# Built-in global load points. OpenClaw has no global load point yet (forgejo
# #135 decision: defer), so it is symlinked only when set in config.
DEFAULT_LOAD_POINTS = {
    "claude": HOME / ".claude" / "CLAUDE.md",
    "codex": HOME / ".codex" / "AGENTS.md",
}

BANNER = "<!-- generated by agent-compose from agent-compose.yaml; do not edit -->"


def _expand(path: str | Path) -> Path:
    return Path(path).expanduser()


def compose(sources: list[Path]) -> str:
    """Concatenate source files into the composed-context body.

    Deterministic (no timestamps) so the drift check (#140) can reproduce it.
    Each section is fenced by a source-path comment for debuggability.
    """
    parts = [BANNER]
    for src in sources:
        text = src.read_text(encoding="utf-8").rstrip("\n")
        parts.append(f"<!-- source: {src} -->\n{text}")
    return "\n\n".join(parts) + "\n"


def install_symlink(dst: Path, target: Path) -> str:
    """Point dst at target, backing up a pre-existing real file to dst.bak.

    Mirrors setup.sh's ensure_link: an existing symlink is replaced, an existing
    regular file is moved aside, parents are created. Returns a log line.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    note = ""
    if dst.is_symlink():
        dst.unlink()
    elif dst.exists():
        backup = dst.with_name(dst.name + ".bak")
        dst.replace(backup)
        note = f" (backed up prior file to {backup})"
    dst.symlink_to(target)
    return f"linked  {dst} -> {target}{note}"


def load_config(config_path: Path) -> dict:
    """Parse the YAML config. Raises RuntimeError if PyYAML is unavailable."""
    try:
        import yaml
    except ModuleNotFoundError as exc:  # pragma: no cover - env-dependent
        raise RuntimeError("PyYAML not available") from exc
    data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{config_path}: top-level YAML must be a mapping")
    return data


def resolve_load_points(config: dict) -> dict[str, Path]:
    """Merge configured load-point overrides over the built-in defaults.

    OpenClaw (and any other extra harness) is included only when its value is
    set and truthy, keeping the deferred third symlink opt-in.
    """
    points = dict(DEFAULT_LOAD_POINTS)
    overrides = config.get("load_points") or {}
    if isinstance(overrides, dict):
        for harness, value in overrides.items():
            if value:
                points[harness] = _expand(value)
            elif harness in points and harness not in DEFAULT_LOAD_POINTS:
                points.pop(harness, None)
    return points


def run(config_path: Path, composed_path: Path, *, dry_run: bool = False) -> int:
    """Compose and wire symlinks. No-op (return 0) when config is absent."""
    if not config_path.is_file():
        print(f"agent-compose: no config at {config_path}; nothing to do (opt-in)")
        return 0

    config = load_config(config_path)
    sources = [_expand(s) for s in (config.get("sources") or [])]
    missing = [s for s in sources if not s.is_file()]
    if missing:
        for src in missing:
            sys.stderr.write(f"agent-compose: source not found: {src}\n")
        return 1

    body = compose(sources)
    load_points = resolve_load_points(config)

    if dry_run:
        print(f"would write {composed_path} ({len(sources)} source(s))")
        for harness, dst in sorted(load_points.items()):
            print(f"would link  {dst} -> {composed_path}  [{harness}]")
        return 0

    composed_path.parent.mkdir(parents=True, exist_ok=True)
    composed_path.write_text(body, encoding="utf-8")
    print(f"wrote   {composed_path} ({len(sources)} source(s))")
    for harness, dst in sorted(load_points.items()):
        print(install_symlink(dst, composed_path) + f"  [{harness}]")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="print the plan, change nothing"
    )
    args = parser.parse_args()
    try:
        return run(CONFIG_PATH, COMPOSED_PATH, dry_run=args.dry_run)
    except RuntimeError as exc:
        sys.stderr.write(f"agent-compose: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
