"""Generated by `generate-seed-skills` from skill frontmatter.

Do not edit by hand. Run `generate-seed-skills` after changing a
skill's seed: frontmatter; check-seed-skills-drift fails on staleness.
"""
from __future__ import annotations

SEED_ALWAYS: list[str] = ['coding-git']

SEED_LANGUAGES: dict[str, dict] = {
    'csharp': {"skill": 'coding-csharp', "extensions": ['.cs']},
    'go': {"skill": 'coding-go', "extensions": ['.go']},
    'javascript': {"skill": 'coding-javascript', "extensions": ['.js', '.mjs', '.cjs', '.jsx', '.ts', '.tsx']},
    'python': {"skill": 'coding-python', "extensions": ['.py', '.pyi']},
    'ruby': {"skill": 'coding-ruby', "extensions": ['.rb']},
    'rust': {"skill": 'coding-rust', "extensions": ['.rs']},
}
