"""Tests for agentic_os.pre_commit.check_code_comments comment discipline.

Every file may carry a contiguous comment header block above the first
content line. After content begins, code allows up to two contiguous comment
lines. YAML is stricter: a key-sorter would drift any later comment away from
its target, so YAML allows comments only in that top header block.
"""
from __future__ import annotations

from pathlib import Path

from agentic_os.pre_commit.check_code_comments import (
    MAX_COMMENT_LINE_CHARS,
    scan_lines,
)


def test_yaml_allows_one_top_comment() -> None:
    lines = ["# regenerated by ward; do not hand-edit", "date: '2026-05-27'"]
    assert scan_lines(Path("snapshot.yaml"), ".yaml", lines) == []


def test_yaml_rejects_comment_below_the_top() -> None:
    lines = ["date: '2026-05-27'", "# this drifts under a sort", "id: W1"]
    violations = scan_lines(Path("snapshot.yaml"), ".yaml", lines)
    assert len(violations) == 1
    assert "snapshot.yaml:2:" in violations[0]


def test_yaml_allows_a_contiguous_top_comment_block() -> None:
    lines = ["# header one", "# header two", "# header three", "date: x"]
    assert scan_lines(Path("snapshot.yaml"), ".yaml", lines) == []


def test_yaml_allows_blank_lines_within_the_top_block() -> None:
    lines = ["# header one", "", "# header two", "date: x"]
    assert scan_lines(Path("snapshot.yaml"), ".yaml", lines) == []


def test_yaml_rejects_comment_after_content_resumes() -> None:
    lines = ["# header", "date: x", "# drifts under a sort", "id: W1"]
    violations = scan_lines(Path("snapshot.yaml"), ".yaml", lines)
    assert len(violations) == 1
    assert "snapshot.yaml:3:" in violations[0]


def test_yaml_top_comment_still_obeys_char_cap() -> None:
    lines = ["# " + "x" * MAX_COMMENT_LINE_CHARS, "date: '2026-05-27'"]
    violations = scan_lines(Path("snapshot.yaml"), ".yaml", lines)
    assert len(violations) == 1
    assert "char cap" in violations[0]


def test_yml_extension_follows_the_same_rule() -> None:
    lines = ["a: 1", "# late note", "b: 2"]
    assert len(scan_lines(Path("c.yml"), ".yml", lines)) == 1


def test_yaml_ignores_bash_comments_in_block_scalar() -> None:
    lines = [
        "runs:",
        "  steps:",
        "    - run: |",
        "        # self-install jq if missing",
        "        apt-get install -y jq",
        "        # resolve the templated url",
        "        echo done",
    ]
    assert scan_lines(Path("action.yml"), ".yml", lines) == []


def test_yaml_flags_real_comment_after_a_block_scalar_ends() -> None:
    lines = [
        "steps:",
        "  - run: |",
        "      # inside the block, fine",
        "      echo hi",
        "  # back at yaml level, drifts under a sort",
        "  - run: echo bye",
    ]
    violations = scan_lines(Path("action.yml"), ".yml", lines)
    assert len(violations) == 1
    assert "action.yml:5:" in violations[0]


def test_yaml_folded_block_scalar_also_shields_comments() -> None:
    lines = ["body: >", "  # not a yaml comment, folded content", "  text"]
    assert scan_lines(Path("c.yaml"), ".yaml", lines) == []


def test_code_still_allows_two_contiguous_comments_after_content() -> None:
    lines = ["x = 1", "# one", "# two", "y = 2"]
    assert scan_lines(Path("m.py"), ".py", lines) == []


def test_code_rejects_three_contiguous_comments_after_content() -> None:
    lines = ["x = 1", "# one", "# two", "# three", "y = 2"]
    assert len(scan_lines(Path("m.py"), ".py", lines)) == 1


def test_code_allows_long_top_header_block() -> None:
    lines = ["# license 1", "# license 2", "# license 3", "# license 4", "import os"]
    assert scan_lines(Path("m.py"), ".py", lines) == []


def test_code_top_header_block_survives_a_shebang() -> None:
    lines = ["#!/usr/bin/env python3", "# h1", "# h2", "# h3", "x = 1"]
    assert scan_lines(Path("m.py"), ".py", lines) == []


def test_kdl_allows_two_contiguous_line_comments_after_content() -> None:
    lines = ["node 1", "// one", "// two", "node 2"]
    assert scan_lines(Path("c.kdl"), ".kdl", lines) == []


def test_kdl_rejects_three_contiguous_line_comments_after_content() -> None:
    lines = ["node 1", "// one", "// two", "// three", "node 2"]
    assert len(scan_lines(Path("c.kdl"), ".kdl", lines)) == 1


def test_kdl_flags_block_comment_run_after_content() -> None:
    lines = ["node 1", "/* one", " * two", " * three */", "node 2"]
    assert len(scan_lines(Path("c.kdl"), ".kdl", lines)) == 1


def test_rust_deref_is_not_a_comment_for_the_char_cap() -> None:
    deref = "    *self.warehouse_stock.entry(item).or_default() += " + "n" * 60
    assert len(deref) > MAX_COMMENT_LINE_CHARS
    lines = ["fn tick() {", deref, "}"]
    assert scan_lines(Path("player.rs"), ".rs", lines) == []


def test_rust_deref_run_is_not_a_contiguous_comment_block() -> None:
    lines = [
        "fn tick() {",
        "    *a += 1;",
        "    *b += 1;",
        "    *c += 1;",
        "}",
    ]
    assert scan_lines(Path("player.rs"), ".rs", lines) == []


def test_c_deref_is_not_a_comment() -> None:
    lines = ["void f(int *p) {", "    *p = 5;", "    *p += 1;", "    *p -= 1;", "}"]
    assert scan_lines(Path("f.c"), ".c", lines) == []


def test_go_deref_is_not_a_comment() -> None:
    lines = ["func f() {", "\t*count += 1", "\t*count += 2", "\t*count += 3", "}"]
    assert scan_lines(Path("f.go"), ".go", lines) == []


def test_rust_block_continuation_is_still_a_comment() -> None:
    lines = ["fn f() {}", "/* one", " * two", " * three", " */", "fn g() {}"]
    violations = scan_lines(Path("m.rs"), ".rs", lines)
    assert len(violations) == 2
    assert "m.rs:4:" in violations[0]
    assert "m.rs:5:" in violations[1]


def test_rust_block_continuation_obeys_the_char_cap() -> None:
    long_continuation = " * " + "x" * MAX_COMMENT_LINE_CHARS
    lines = ["fn f() {}", "/* one", long_continuation, " */", "fn g() {}"]
    violations = scan_lines(Path("m.rs"), ".rs", lines)
    assert len(violations) == 2
    assert "char cap" in violations[0]
    assert "m.rs:3:" in violations[0]


def test_rust_deref_after_a_closed_block_is_not_a_comment() -> None:
    lines = [
        "fn f() {",
        "    /* set up the counters */",
        "    *a += 1;",
        "    *b += 1;",
        "    *c += 1;",
        "}",
    ]
    assert scan_lines(Path("m.rs"), ".rs", lines) == []


def test_rust_block_opened_mid_line_shields_the_next_lines() -> None:
    lines = ["fn f() {} /* one", " * two", " * three", " */", "fn g() {}"]
    violations = scan_lines(Path("m.rs"), ".rs", lines)
    assert len(violations) == 1
    assert "m.rs:4:" in violations[0]


def test_block_open_inside_a_string_does_not_shield_a_deref() -> None:
    lines = [
        "fn f() {",
        '    let s = "/*";',
        "    *a += 1;",
        "    *b += 1;",
        "    *c += 1;",
        "}",
    ]
    assert scan_lines(Path("m.rs"), ".rs", lines) == []


def test_block_open_inside_a_line_comment_does_not_shield_a_deref() -> None:
    lines = [
        "fn f() {",
        "    // see /* below",
        "    *a += 1;",
        "    *b += 1;",
        "    *c += 1;",
        "}",
    ]
    assert scan_lines(Path("m.rs"), ".rs", lines) == []
