#!/usr/bin/env python3
"""Generate role-centered frontier and low-context budget reports.

The checked-in role-seat YAML snapshots are the measurement evidence. This
generator groups them by the AOS-owned layout model class, renders one report
per canonical role, and computes the class delta without copying arithmetic
into prose. `--check` makes the committed reports drift-proof.

See docs/context-budget-role-seat.md.
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path

from agentic_os.context_budget_role_seat import (
    load_aos_layout_model_classes,
    load_snapshot,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = _REPO_ROOT / "docs"
ROLE_BOARD_PATH = _REPO_ROOT / "aos-cli" / "role-personalities.json"
GENERATED_MARKER = (
    "<!-- GENERATED by generate-context-budget-role-reports - "
    "do not hand-edit. -->"
)
GENERATED_HEADER = (
    f"{GENERATED_MARKER}\n"
    "<!-- Regenerate: ward exec gen-context-budget-role-reports. -->\n"
)
MODEL_CLASSES = ("frontier", "low-context")


def _mapping(value: object, label: str) -> Mapping[str, object]:
    if not isinstance(value, dict):
        raise RuntimeError(f"{label} must be a mapping")
    return value


def load_canonical_roles(path: Path = ROLE_BOARD_PATH) -> tuple[str, ...]:
    """Load the ordered role ids from the AOS role-personality board."""
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"read role board {path}: {exc}") from exc
    if not isinstance(document, dict) or not isinstance(document.get("roles"), list):
        raise RuntimeError(f"{path}: role board must contain a roles list")
    roles: list[str] = []
    for raw in document["roles"]:
        if not isinstance(raw, dict) or not isinstance(raw.get("role"), str):
            raise RuntimeError(f"{path}: role board contains a malformed role")
        roles.append(raw["role"])
    if document.get("role_count") != len(roles) or len(set(roles)) != len(roles):
        raise RuntimeError(f"{path}: role board count or uniqueness is invalid")
    return tuple(roles)


def _snapshot_identity(path: Path, seats: Iterable[str]) -> tuple[str, str]:
    prefix = "context-budget-"
    for seat in sorted(seats, key=len, reverse=True):
        suffix = f"-{seat}-current.yaml"
        if path.name.startswith(prefix) and path.name.endswith(suffix):
            role = path.name[len(prefix) : -len(suffix)]
            if role:
                return role, seat
    raise RuntimeError(f"{path}: current snapshot filename has no supported AOS seat")


def load_role_snapshots(
    docs_dir: Path,
    roles: Iterable[str],
    layouts: Mapping[str, str],
) -> dict[str, dict[str, dict[str, object]]]:
    """Load and validate every current role-seat snapshot."""
    role_order = tuple(roles)
    expected_roles = set(role_order)
    grouped: dict[str, dict[str, dict[str, object]]] = {
        role: {} for role in role_order
    }
    for path in sorted(docs_dir.glob("context-budget-*-current.yaml")):
        role, seat = _snapshot_identity(path, layouts)
        if role not in expected_roles:
            raise RuntimeError(f"{path}: snapshot role {role!r} is not canonical")
        snapshot = load_snapshot(path)
        subject = _mapping(snapshot.get("subject"), f"{path}: subject")
        if subject.get("role") != role or subject.get("seat") != seat:
            raise RuntimeError(f"{path}: snapshot subject does not match its filename")
        bundle = _mapping(snapshot.get("bundle"), f"{path}: bundle")
        if bundle.get("model_class") != layouts[seat]:
            raise RuntimeError(
                f"{path}: expected model class {layouts[seat]!r} for seat {seat!r}"
            )
        grouped[role][seat] = snapshot
    for role, snapshots in grouped.items():
        if not snapshots:
            raise RuntimeError(f"role {role!r} has no current seats")
        if not any(
            layouts[seat] == "frontier"
            for seat in snapshots
        ):
            raise RuntimeError(f"role {role!r} has no frontier snapshot")
    return grouped


def _nested_int(snapshot: Mapping[str, object], *keys: str) -> int:
    value: object = snapshot
    for key in keys:
        value = _mapping(value, ".".join(keys)).get(key)
    if not isinstance(value, int):
        raise RuntimeError(f"snapshot {'.'.join(keys)} must be an integer")
    return value


def _composed_count(snapshot: Mapping[str, object]) -> int:
    eager = _mapping(
        _mapping(snapshot.get("breakdown"), "snapshot breakdown").get("eager"),
        "snapshot eager breakdown",
    )
    composed = eager.get("role-composed-frontmatter")
    if composed is None:
        return 0
    return _nested_int({"value": composed}, "value", "components")


def _role_label(role: str) -> str:
    if role == "qa":
        return "QA"
    if role == "strats":
        return "Portfolio Strategist"
    if role == "content":
        return "Content Manager"
    return role.replace("-", " ")


def _seat_label(seat: str) -> str:
    if seat == "opencode":
        return "OpenCode"
    return seat.capitalize()


def _range_text(values: Iterable[int]) -> str:
    ordered = sorted(set(values))
    if not ordered:
        raise RuntimeError("cannot render an empty numeric range")
    if len(ordered) == 1:
        return f"{ordered[0]:,}"
    return f"{ordered[0]:,} to {ordered[-1]:,}"


def _class_snapshots(
    snapshots: Mapping[str, dict[str, object]],
    layouts: Mapping[str, str],
    model_class: str,
) -> list[tuple[str, dict[str, object]]]:
    selected = [
        (seat, snapshots[seat])
        for seat, declared_class in layouts.items()
        if declared_class == model_class and seat in snapshots
    ]
    return selected


def _render_class_line(
    role: str,
    model_class: str,
    selected: list[tuple[str, dict[str, object]]],
) -> list[str]:
    heading = "Frontier" if model_class == "frontier" else "Low-context"
    links = [
        f"[{_seat_label(seat)} {_nested_int(snapshot, 'totals', 'eager', 'tokens'):,}]"
        f"(context-budget-{role}-{seat}-current.yaml)"
        for seat, snapshot in selected
    ]
    lazy = _range_text(
        _nested_int(snapshot, "totals", "lazy", "tokens")
        for _, snapshot in selected
    )
    composed = _range_text(_composed_count(snapshot) for _, snapshot in selected)
    lines = [f"* **{heading} {_role_label(role)}** -"]
    for index, link in enumerate(links):
        suffix = "," if index < len(links) - 1 else f", lazy {lazy}, {composed} composed."
        lines.append(f"  {link}{suffix}")
    return lines


def _change_text(
    frontier: Iterable[int],
    low_context: Iterable[int],
    unit: str,
) -> str:
    frontier_values = tuple(frontier)
    low_values = tuple(low_context)
    differences = [
        frontier_value - low_value
        for frontier_value in frontier_values
        for low_value in low_values
    ]
    low = min(differences)
    high = max(differences)
    if low >= 0:
        return f"saves {_range_text(differences)} {unit}"
    if high <= 0:
        return f"adds {_range_text(abs(value) for value in differences)} {unit}"
    return f"changes by {-high:,} to {-low:,} {unit}"


def render_role_report(
    role: str,
    snapshots: Mapping[str, dict[str, object]],
    layouts: Mapping[str, str],
) -> str:
    """Render one deterministic role report and its class-level delta."""
    by_class = {
        model_class: _class_snapshots(snapshots, layouts, model_class)
        for model_class in MODEL_CLASSES
    }
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        f"# Current {_role_label(role)} context budget",
        "",
    ]
    for model_class in MODEL_CLASSES:
        if by_class[model_class]:
            lines.extend(_render_class_line(role, model_class, by_class[model_class]))
    frontier = by_class["frontier"]
    low_context = by_class["low-context"]
    if low_context:
        eager_change = _change_text(
            (
                _nested_int(snapshot, "totals", "eager", "tokens")
                for _, snapshot in frontier
            ),
            (
                _nested_int(snapshot, "totals", "eager", "tokens")
                for _, snapshot in low_context
            ),
            "tokens",
        )
        lazy_change = _change_text(
            (
                _nested_int(snapshot, "totals", "lazy", "tokens")
                for _, snapshot in frontier
            ),
            (
                _nested_int(snapshot, "totals", "lazy", "tokens")
                for _, snapshot in low_context
            ),
            "tokens",
        )
        frontier_composed = _range_text(
            _composed_count(snapshot) for _, snapshot in frontier
        )
        low_composed = _range_text(
            _composed_count(snapshot) for _, snapshot in low_context
        )
        lines.extend(
            [
            f"* **Low-context diff** - eager {eager_change}, lazy {lazy_change}, "
            f"composed sources {frontier_composed} -> {low_composed}.",
            "",
            "The programmatic diff compares every frontier seat with every "
            "low-context seat.",
            ]
        )
    else:
        lines.extend(
            [
                "",
                "Only frontier snapshots are available for this role.",
            ]
        )
    lines.extend(
        [
            "",
            "## See also",
            "",
            "* [Current role-class inventory](context-budget-role-seat-current.md)",
            "* [Snapshot contract](context-budget-role-seat.md)",
        ]
    )
    return "\n".join(lines) + "\n"


def build_reports(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
    layouts: Mapping[str, str] | None = None,
) -> dict[Path, str]:
    """Build every expected report without mutating the filesystem."""
    role_order = tuple(roles) if roles is not None else load_canonical_roles()
    layout_classes = dict(layouts or load_aos_layout_model_classes())
    snapshots = load_role_snapshots(docs_dir, role_order, layout_classes)
    return {
        docs_dir / f"context-budget-role-{role}-current.md": render_role_report(
            role, snapshots[role], layout_classes
        )
        for role in role_order
    }


def _stale_generated_reports(docs_dir: Path, expected: set[Path]) -> list[Path]:
    stale: list[Path] = []
    for path in docs_dir.glob("context-budget-role-*-current.md"):
        if path in expected or not path.is_file():
            continue
        if path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            stale.append(path)
    return sorted(stale)


def generate(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
    layouts: Mapping[str, str] | None = None,
) -> int:
    reports = build_reports(docs_dir, roles, layouts)
    for path, content in reports.items():
        path.write_text(content, encoding="utf-8")
    for path in _stale_generated_reports(docs_dir, set(reports)):
        path.unlink()
    print(f"context-budget-role-reports: wrote {len(reports)} role reports")
    return 0


def check_drift(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
    layouts: Mapping[str, str] | None = None,
) -> int:
    reports = build_reports(docs_dir, roles, layouts)
    stale = _stale_generated_reports(docs_dir, set(reports))
    drifted = [
        (path, content, path.read_text(encoding="utf-8") if path.exists() else "")
        for path, content in reports.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if not drifted and not stale:
        print(f"context-budget-role-reports: {len(reports)} reports in sync")
        return 0
    for path in stale:
        sys.stderr.write(f"context-budget-role-reports: stale generated report {path.name}\n")
    for path, expected, actual in drifted:
        sys.stderr.write(
            f"context-budget-role-reports: {path.name} is missing, stale, or "
            "hand-edited\n"
        )
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"{path.name} (on disk)",
            tofile="expected (fresh generate)",
            lineterm="",
        )
        for line in list(diff)[:24]:
            sys.stderr.write(line + "\n")
    sys.stderr.write(
        "Run `ward exec gen-context-budget-role-reports` to regenerate.\n"
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated role reports match the current YAML snapshots",
    )
    parser.add_argument(
        "--docs",
        type=Path,
        default=DOCS_DIR,
        help="directory containing the snapshots and generated reports",
    )
    args = parser.parse_args()
    try:
        return check_drift(args.docs) if args.check else generate(args.docs)
    except RuntimeError as exc:
        sys.stderr.write(f"context-budget-role-reports: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
