#!/usr/bin/env python3
"""Generate policy-scoped role and cross-role context-budget reports.

The checked-in role-seat YAML snapshots are the measurement evidence. This
generator validates every snapshot, groups the selected evidence by the
AOS-owned layout model class, renders one report per canonical role plus the
cross-role index, and computes class deltas without copying arithmetic into
prose. `--check` makes the committed reports drift-proof.

See docs/context-budget-role-seat.md.
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
import textwrap
from collections.abc import Iterable, Mapping
from pathlib import Path

from agentic_os.context_budget_role_seat import (
    load_aos_layout_model_classes,
    load_snapshot,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = _REPO_ROOT / "docs"
ROLE_BOARD_PATH = _REPO_ROOT / "aos-cli" / "role-personalities.json"
INVENTORY_POLICY_PATH = (
    _REPO_ROOT / "agentic_os" / "context_budget_inventory_policy.json"
)
INVENTORY_POLICY_FORMAT = "agentic-os.context-budget-inventory-policy.v1"
GENERATED_MARKER = (
    "<!-- GENERATED by generate-context-budget-role-reports - "
    "do not hand-edit. -->"
)
GENERATED_HEADER = (
    f"{GENERATED_MARKER}\n"
    "<!-- Regenerate: ward exec gen-context-budget-role-reports. -->\n"
)
MODEL_CLASSES = ("frontier", "low-context")


def _mapping(value: object, label: str) -> Mapping[str, object]:
    if not isinstance(value, dict):
        raise RuntimeError(f"{label} must be a mapping")
    return value


def load_canonical_roles(path: Path = ROLE_BOARD_PATH) -> tuple[str, ...]:
    """Load the ordered role ids from the AOS role-personality board."""
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"read role board {path}: {exc}") from exc
    if not isinstance(document, dict) or not isinstance(document.get("roles"), list):
        raise RuntimeError(f"{path}: role board must contain a roles list")
    roles: list[str] = []
    for raw in document["roles"]:
        if not isinstance(raw, dict) or not isinstance(raw.get("role"), str):
            raise RuntimeError(f"{path}: role board contains a malformed role")
        roles.append(raw["role"])
    if document.get("role_count") != len(roles) or len(set(roles)) != len(roles):
        raise RuntimeError(f"{path}: role board count or uniqueness is invalid")
    return tuple(roles)


def _supported_model_classes(layouts: Mapping[str, str]) -> tuple[str, ...]:
    discovered = set(layouts.values())
    unknown = discovered.difference(MODEL_CLASSES)
    if unknown:
        raise RuntimeError(
            f"layout registry contains unsupported model classes: {sorted(unknown)}"
        )
    return tuple(
        model_class for model_class in MODEL_CLASSES if model_class in discovered
    )


def validate_inventory_model_classes(
    value: object,
    roles: Iterable[str],
    model_classes: Iterable[str],
    *,
    label: str = "inventory model-class policy",
) -> dict[str, tuple[str, ...]]:
    """Validate explicit role scopes without supplying unlisted defaults."""
    if not isinstance(value, dict):
        raise RuntimeError(f"{label} must be a mapping")
    canonical_roles = set(roles)
    class_order = tuple(model_classes)
    supported_classes = set(class_order)
    policy: dict[str, tuple[str, ...]] = {}
    for raw_role, raw_classes in value.items():
        if not isinstance(raw_role, str) or raw_role not in canonical_roles:
            raise RuntimeError(f"{label} contains unknown role {raw_role!r}")
        if not isinstance(raw_classes, list) or not raw_classes:
            raise RuntimeError(
                f"{label} role {raw_role!r} must select at least one class"
            )
        if not all(isinstance(model_class, str) for model_class in raw_classes):
            raise RuntimeError(f"{label} role {raw_role!r} classes must be text")
        if len(set(raw_classes)) != len(raw_classes):
            raise RuntimeError(
                f"{label} role {raw_role!r} contains duplicate classes"
            )
        unknown = set(raw_classes).difference(supported_classes)
        if unknown:
            raise RuntimeError(
                f"{label} role {raw_role!r} contains unsupported classes: "
                f"{sorted(unknown)}"
            )
        selected = set(raw_classes)
        policy[raw_role] = tuple(
            model_class for model_class in class_order if model_class in selected
        )
    return policy


def load_inventory_model_classes(
    path: Path = INVENTORY_POLICY_PATH,
    roles: Iterable[str] | None = None,
    model_classes: Iterable[str] | None = None,
) -> dict[str, tuple[str, ...]]:
    """Load and validate the AOS-owned aggregate measurement policy."""
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"read inventory model-class policy {path}: {exc}") from exc
    if (
        not isinstance(document, dict)
        or document.get("format") != INVENTORY_POLICY_FORMAT
        or set(document) != {"format", "inventory_model_classes"}
    ):
        raise RuntimeError(f"{path}: malformed inventory model-class policy")
    canonical_roles = tuple(roles) if roles is not None else load_canonical_roles()
    if model_classes is None:
        layout_classes = load_aos_layout_model_classes()
        supported = _supported_model_classes(layout_classes)
    else:
        supported = tuple(model_classes)
    return validate_inventory_model_classes(
        document["inventory_model_classes"],
        canonical_roles,
        supported,
        label=str(path),
    )


def _snapshot_identity(path: Path, seats: Iterable[str]) -> tuple[str, str]:
    prefix = "context-budget-"
    for seat in sorted(seats, key=len, reverse=True):
        suffix = f"-{seat}-current.yaml"
        if path.name.startswith(prefix) and path.name.endswith(suffix):
            role = path.name[len(prefix) : -len(suffix)]
            if role:
                return role, seat
    raise RuntimeError(f"{path}: current snapshot filename has no supported AOS seat")


def load_role_snapshots(
    docs_dir: Path,
    roles: Iterable[str],
    layouts: Mapping[str, str],
) -> dict[str, dict[str, dict[str, object]]]:
    """Load and validate every current role-seat snapshot."""
    role_order = tuple(roles)
    expected_roles = set(role_order)
    grouped: dict[str, dict[str, dict[str, object]]] = {
        role: {} for role in role_order
    }
    for path in sorted(docs_dir.glob("context-budget-*-current.yaml")):
        role, seat = _snapshot_identity(path, layouts)
        if role not in expected_roles:
            raise RuntimeError(f"{path}: snapshot role {role!r} is not canonical")
        snapshot = load_snapshot(path)
        subject = _mapping(snapshot.get("subject"), f"{path}: subject")
        if subject.get("role") != role or subject.get("seat") != seat:
            raise RuntimeError(f"{path}: snapshot subject does not match its filename")
        bundle = _mapping(snapshot.get("bundle"), f"{path}: bundle")
        if bundle.get("model_class") != layouts[seat]:
            raise RuntimeError(
                f"{path}: expected model class {layouts[seat]!r} for seat {seat!r}"
            )
        grouped[role][seat] = snapshot
    for role, snapshots in grouped.items():
        if not snapshots:
            raise RuntimeError(f"role {role!r} has no current seats")
        if not any(
            layouts[seat] == "frontier"
            for seat in snapshots
        ):
            raise RuntimeError(f"role {role!r} has no frontier snapshot")
    return grouped


def _nested_int(snapshot: Mapping[str, object], *keys: str) -> int:
    value: object = snapshot
    for key in keys:
        value = _mapping(value, ".".join(keys)).get(key)
    if not isinstance(value, int):
        raise RuntimeError(f"snapshot {'.'.join(keys)} must be an integer")
    return value


def _composed_count(snapshot: Mapping[str, object]) -> int:
    eager = _mapping(
        _mapping(snapshot.get("breakdown"), "snapshot breakdown").get("eager"),
        "snapshot eager breakdown",
    )
    composed = eager.get("role-composed-frontmatter")
    if composed is None:
        return 0
    return _nested_int({"value": composed}, "value", "components")


def _role_label(role: str) -> str:
    if role == "qa":
        return "QA"
    if role == "strats":
        return "Portfolio Strategist"
    if role == "content":
        return "Content Manager"
    return role.replace("-", " ")


def _role_title(role: str) -> str:
    if role == "qa":
        return "QA"
    if role == "strats":
        return "Portfolio Strategist"
    if role == "content":
        return "Content Manager"
    return role.replace("-", " ").title()


def _seat_label(seat: str) -> str:
    if seat == "opencode":
        return "OpenCode"
    return seat.capitalize()


def _range_text(values: Iterable[int]) -> str:
    ordered = sorted(set(values))
    if not ordered:
        raise RuntimeError("cannot render an empty numeric range")
    if len(ordered) == 1:
        return f"{ordered[0]:,}"
    return f"{ordered[0]:,} to {ordered[-1]:,}"


def _class_snapshots(
    snapshots: Mapping[str, dict[str, object]],
    layouts: Mapping[str, str],
    model_class: str,
) -> list[tuple[str, dict[str, object]]]:
    selected = [
        (seat, snapshots[seat])
        for seat, declared_class in layouts.items()
        if declared_class == model_class and seat in snapshots
    ]
    return selected


def _aggregate_snapshots(
    role: str,
    snapshots: Mapping[str, dict[str, object]],
    layouts: Mapping[str, str],
    model_classes: Iterable[str],
) -> dict[str, dict[str, object]]:
    selected_classes = set(model_classes)
    selected = {
        seat: snapshot
        for seat, snapshot in snapshots.items()
        if layouts[seat] in selected_classes
    }
    if not any(layouts[seat] == "frontier" for seat in selected):
        raise RuntimeError(
            f"role {role!r} has no frontier snapshot after inventory filtering"
        )
    return selected


def _scope_text(model_classes: Iterable[str]) -> str:
    classes = tuple(model_classes)
    if len(classes) == 1:
        return f"{classes[0]} only"
    return " and ".join(classes)


def _scope_seat_text(model_classes: Iterable[str]) -> str:
    classes = tuple(model_classes)
    if len(classes) == 1:
        return f"{classes[0]} seats only"
    return f"{_scope_text(classes)} seats"


def _wrapped_lines(text: str, *, subsequent_indent: str = "") -> list[str]:
    return textwrap.wrap(
        text,
        width=88,
        subsequent_indent=subsequent_indent,
        break_long_words=False,
        break_on_hyphens=False,
    )


def _render_class_line(
    role: str,
    model_class: str,
    selected: list[tuple[str, dict[str, object]]],
) -> list[str]:
    heading = "Frontier" if model_class == "frontier" else "Low-context"
    links = [
        f"[{_seat_label(seat)} {_nested_int(snapshot, 'totals', 'eager', 'tokens'):,}]"
        f"(context-budget-{role}-{seat}-current.yaml)"
        for seat, snapshot in selected
    ]
    lazy = _range_text(
        _nested_int(snapshot, "totals", "lazy", "tokens")
        for _, snapshot in selected
    )
    composed = _range_text(_composed_count(snapshot) for _, snapshot in selected)
    lines = [f"* **{heading} {_role_label(role)}** -"]
    for index, link in enumerate(links):
        suffix = "," if index < len(links) - 1 else f", lazy {lazy}, {composed} composed."
        lines.append(f"  {link}{suffix}")
    return lines


def _change_text(
    frontier: Iterable[int],
    low_context: Iterable[int],
    unit: str,
) -> str:
    frontier_values = tuple(frontier)
    low_values = tuple(low_context)
    differences = [
        frontier_value - low_value
        for frontier_value in frontier_values
        for low_value in low_values
    ]
    low = min(differences)
    high = max(differences)
    if low >= 0:
        return f"saves {_range_text(differences)} {unit}"
    if high <= 0:
        return f"adds {_range_text(abs(value) for value in differences)} {unit}"
    return f"changes by {-high:,} to {-low:,} {unit}"


def render_role_report(
    role: str,
    snapshots: Mapping[str, dict[str, object]],
    layouts: Mapping[str, str],
    inventory_model_classes: Iterable[str],
    supported_model_classes: Iterable[str],
) -> str:
    """Render one deterministic role report and its class-level delta."""
    scope = tuple(inventory_model_classes)
    supported = tuple(supported_model_classes)
    by_class = {
        model_class: _class_snapshots(snapshots, layouts, model_class)
        for model_class in MODEL_CLASSES
    }
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        f"# Current {_role_label(role)} context budget",
        "",
    ]
    if scope == supported:
        lines.extend(
            _wrapped_lines(
                "Aggregate inventory scope measures all AOS-supported model classes."
            )
        )
    else:
        lines.extend(
            _wrapped_lines(
                "Aggregate inventory scope intentionally measures "
                f"{_scope_seat_text(scope)}. This reporting scope is separate from "
                "runtime compatibility, and excluded snapshots remain independently "
                "valid evidence."
            )
        )
    lines.append("")
    for model_class in MODEL_CLASSES:
        if by_class[model_class]:
            lines.extend(_render_class_line(role, model_class, by_class[model_class]))
    frontier = by_class["frontier"]
    low_context = by_class["low-context"]
    if low_context:
        eager_change = _change_text(
            (
                _nested_int(snapshot, "totals", "eager", "tokens")
                for _, snapshot in frontier
            ),
            (
                _nested_int(snapshot, "totals", "eager", "tokens")
                for _, snapshot in low_context
            ),
            "tokens",
        )
        lazy_change = _change_text(
            (
                _nested_int(snapshot, "totals", "lazy", "tokens")
                for _, snapshot in frontier
            ),
            (
                _nested_int(snapshot, "totals", "lazy", "tokens")
                for _, snapshot in low_context
            ),
            "tokens",
        )
        frontier_composed = _range_text(
            _composed_count(snapshot) for _, snapshot in frontier
        )
        low_composed = _range_text(
            _composed_count(snapshot) for _, snapshot in low_context
        )
        lines.extend(
            [
            f"* **Low-context diff** - eager {eager_change}, lazy {lazy_change}, "
            f"composed sources {frontier_composed} -> {low_composed}.",
            "",
            "The programmatic diff compares every frontier seat with every "
            "low-context seat.",
            ]
        )
    elif "low-context" in scope:
        lines.extend(
            [
                "",
                "Only frontier snapshots are available for this role.",
            ]
        )
    lines.extend(
        [
            "",
            "## See also",
            "",
            "* [Current role-class inventory](context-budget-role-seat-current.md)",
            "* [Snapshot contract](context-budget-role-seat.md)",
        ]
    )
    return "\n".join(lines) + "\n"


def render_inventory_index(
    roles: Iterable[str],
    inventory_model_classes: Mapping[str, tuple[str, ...]],
) -> str:
    """Render the cross-role aggregate measurement inventory."""
    role_order = tuple(roles)
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        "# Current role-class context inventory",
        "",
    ]
    lines.extend(
        _wrapped_lines(
            f"The {len(role_order)} canonical Agent Compose Core Roster roles use an "
            "AOS-owned policy to select which model classes enter aggregate context "
            "reports. Every checked-in current snapshot is validated before that "
            "policy is applied, so excluded snapshots remain loadable evidence."
        )
    )
    lines.append("")
    lines.extend(
        _wrapped_lines(
            "Aggregate measurement scope is separate from runtime compatibility. "
            "Role composition and seat layouts remain the runtime sources of truth."
        )
    )
    lines.append("")
    lines.extend(
        _wrapped_lines(
            "Every entry uses the deterministic characters-divided-by-four token "
            "proxy. The role reports and available class deltas are generated with "
            "`ward exec gen-context-budget-role-reports`."
        )
    )
    lines.extend(["", "## Roles", ""])
    for role in role_order:
        lines.extend(
            _wrapped_lines(
                f"* [{_role_title(role)}](context-budget-role-{role}-current.md) - "
                "aggregate measurement scope: "
                f"{_scope_text(inventory_model_classes[role])}.",
                subsequent_indent="  ",
            )
        )
    lines.append("")
    lines.extend(
        _wrapped_lines(
            "Goose and OpenCode snapshots have equal token totals where both are "
            "checked in because each receives the same catalog and AGENTS cascade. "
            "Their projection paths and payload hashes remain distinct."
        )
    )
    lines.extend(["", "## Interpretation", ""])
    lines.extend(
        _wrapped_lines(
            "The AGENTS cascade is the dominant eager cost in every seat. Low-context "
            "selection substantially cuts lazy retrieval and trims eager routing "
            "metadata, but the inherited AGENTS surface keeps low-context snapshots "
            "above the legacy 5,000-token generic harness budget. Role-composed "
            "metadata ranges from the small Community set through the broad Director "
            "catalog. Lazy totals describe available retrieval, not startup prompt "
            "load."
        )
    )
    lines.extend(
        [
            "",
            "## See also",
            "",
            "* [Role-seat snapshot contract](context-budget-role-seat.md) - capture,",
            "  comparison, and failure rules.",
            "* [Context-budget report](context-budget.md) - component definitions and",
            "  token proxy.",
        ]
    )
    return "\n".join(lines) + "\n"


def build_reports(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
    layouts: Mapping[str, str] | None = None,
    inventory_model_classes: Mapping[str, object] | None = None,
) -> dict[Path, str]:
    """Build every expected report without mutating the filesystem."""
    role_order = tuple(roles) if roles is not None else load_canonical_roles()
    layout_classes = dict(layouts or load_aos_layout_model_classes())
    supported_model_classes = _supported_model_classes(layout_classes)
    if inventory_model_classes is None:
        configured_scopes = load_inventory_model_classes(
            roles=load_canonical_roles(),
            model_classes=supported_model_classes,
        )
    else:
        configured_scopes = validate_inventory_model_classes(
            dict(inventory_model_classes),
            role_order,
            supported_model_classes,
        )
    role_scopes = {
        role: configured_scopes.get(role, supported_model_classes)
        for role in role_order
    }
    snapshots = load_role_snapshots(docs_dir, role_order, layout_classes)
    reports = {
        docs_dir / f"context-budget-role-{role}-current.md": render_role_report(
            role,
            _aggregate_snapshots(
                role,
                snapshots[role],
                layout_classes,
                role_scopes[role],
            ),
            layout_classes,
            role_scopes[role],
            supported_model_classes,
        )
        for role in role_order
    }
    reports[docs_dir / "context-budget-role-seat-current.md"] = render_inventory_index(
        role_order,
        role_scopes,
    )
    return reports


def _stale_generated_reports(docs_dir: Path, expected: set[Path]) -> list[Path]:
    stale: list[Path] = []
    for path in docs_dir.glob("context-budget-role-*-current.md"):
        if path in expected or not path.is_file():
            continue
        if path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            stale.append(path)
    return sorted(stale)


def generate(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
    layouts: Mapping[str, str] | None = None,
    inventory_model_classes: Mapping[str, object] | None = None,
) -> int:
    reports = build_reports(docs_dir, roles, layouts, inventory_model_classes)
    for path, content in reports.items():
        path.write_text(content, encoding="utf-8")
    for path in _stale_generated_reports(docs_dir, set(reports)):
        path.unlink()
    print(f"context-budget-role-reports: wrote {len(reports)} inventory documents")
    return 0


def check_drift(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
    layouts: Mapping[str, str] | None = None,
    inventory_model_classes: Mapping[str, object] | None = None,
) -> int:
    reports = build_reports(docs_dir, roles, layouts, inventory_model_classes)
    stale = _stale_generated_reports(docs_dir, set(reports))
    drifted = [
        (path, content, path.read_text(encoding="utf-8") if path.exists() else "")
        for path, content in reports.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if not drifted and not stale:
        print(f"context-budget-role-reports: {len(reports)} inventory documents in sync")
        return 0
    for path in stale:
        sys.stderr.write(f"context-budget-role-reports: stale generated report {path.name}\n")
    for path, expected, actual in drifted:
        sys.stderr.write(
            f"context-budget-role-reports: {path.name} is missing, stale, or "
            "hand-edited\n"
        )
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"{path.name} (on disk)",
            tofile="expected (fresh generate)",
            lineterm="",
        )
        for line in list(diff)[:24]:
            sys.stderr.write(line + "\n")
    sys.stderr.write(
        "Run `ward exec gen-context-budget-role-reports` to regenerate.\n"
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated role reports match the current YAML snapshots",
    )
    parser.add_argument(
        "--docs",
        type=Path,
        default=DOCS_DIR,
        help="directory containing the snapshots and generated reports",
    )
    args = parser.parse_args()
    try:
        return check_drift(args.docs) if args.check else generate(args.docs)
    except RuntimeError as exc:
        sys.stderr.write(f"context-budget-role-reports: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
