"""Generate the committed ``ward ops aws`` command reference."""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = REPO_ROOT / "docs" / "ward-ops-aws-reference.md"


def _ward_help(*args: str) -> str:
    env = os.environ.copy()
    env["WARD_CONFIG_REF"] = f"file://{REPO_ROOT / '.ward'}"
    proc = subprocess.run(
        ["ward", *args, "--help"],
        cwd=REPO_ROOT,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout.rstrip()


def render_doc() -> str:
    sections = (
        ("ward ops aws", _ward_help("ops", "aws")),
        ("ward ops aws ssm", _ward_help("ops", "aws", "ssm")),
    )
    lines = [
        "<!-- GENERATED by generate-ward-aws-reference - do not hand-edit. -->",
        "<!-- Regenerate: ward exec gen-ward-ops-aws-reference -->",
        "",
        "# ward ops aws - committed reference",
        "",
        "Generated from the launch-selected AOS `.ward` bundle. This reference keeps",
        "the guarded AWS command names discoverable without requiring a live AWS call.",
        "",
        "The full `guardfile.aws.kdl` sorts before the role-only engineer source and",
        "therefore owns the shared public command path. Ward role composition selects",
        "the narrower source for engineer containers, which keeps SSM writes withheld.",
    ]
    for heading, help_text in sections:
        lines.extend(("", f"## {heading}", "", "```text", help_text, "```"))
    lines.extend(
        (
            "",
            "## See also",
            "",
            "* [Ward spec bundle](ward-specs.md) - the source bundle behind this surface.",
            "* [Role surface tiers](role-surface-tiers.md) - which roles receive AWS access.",
        )
    )
    return "\n".join(lines) + "\n"


def generate(doc_path: Path = DOC_PATH) -> int:
    doc_path.write_text(render_doc(), encoding="utf-8")
    print(f"generate-ward-aws-reference: wrote {doc_path}")
    return 0


def check_drift(doc_path: Path = DOC_PATH) -> int:
    expected = render_doc()
    actual = doc_path.read_text(encoding="utf-8") if doc_path.exists() else ""
    if actual == expected:
        print(f"ward-aws-reference-drift: {doc_path.name} in sync")
        return 0
    sys.stderr.write(
        "ward-aws-reference-drift: reference is missing or stale. "
        "Run `ward exec gen-ward-ops-aws-reference`.\n"
    )
    for line in list(
        difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"{doc_path.name} (on disk)",
            tofile="expected (fresh generate)",
            lineterm="",
        )
    )[:40]:
        sys.stderr.write(line + "\n")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args()
    return check_drift() if args.check else generate()


if __name__ == "__main__":
    sys.exit(main())
