#!/usr/bin/env python3
"""Compose global agent-context files from machine- and harness-scoped sources.

agent-compose normally synthesizes one canonical context file
(`~/.config/agent-compose/COMPOSED.md`) and points each harness's global load
point at it by symlink. Sources may optionally declare `harnesses` in YAML
frontmatter. When configured harnesses select different source slices, the
composer writes `COMPOSED.<harness>.md` files instead. Shared sources remain
shared by default, and byte-identical slices still use one file.

Sources are either listed explicitly or discovered by walking declared roots
for files named AGENTS.COMPOSE.md (forgejo #136). AGENTS.COMPOSE.md is the
disjoint source convention: it holds always-global doctrine and is never loaded
by a harness's own AGENTS.md/CLAUDE.md cascade, so composing it in does not
double-load.

Scope filtering (#137) selects which sources compose on this machine. The
machine declares `scopes`; each source declares its own `scopes` in YAML
frontmatter; a source composes iff the two sets intersect. Filtering is itself
opt-in: a config with no `scopes` key composes every source. Activation overall
is opt-in too: with no config file present the composer is a total no-op, so
every harness behaves exactly as it does without agent-compose installed.

Source frontmatter (stripped from composed output, never leaks into context):

    ---
    scopes: [kai-public, work]
    harnesses: [claude, codex]
    ---
    # always-global doctrine ...

Composed output is read from ~/.config/agent-compose, not from a source's own
repo, so two more repo-local conventions are rewritten at compose time (sources
on disk are never touched). Relative markdown links are absolutized against the
source's directory so ``](README.md)`` stays followable, and ``## See also``
trifecta navigation sections are dropped as pure in-repo navigation. Both are
symmetric with the frontmatter strip: what is meaningful only inside the source
repo never reaches the composed context.

Per-harness section overrides let one harness diverge from a shared source
without forking the whole file. An override is a sibling named
``AGENTS.<harness>.md`` in the base source's own directory; it declares no
target path, so it can only patch the base it sits beside. Its sections are
keyed by verbatim heading: a heading already in the base replaces that section,
a new heading is appended. Headings are unique within a single file, which is
why the directory binding is enough to anchor unambiguously. A source's
overrides feed the divergence signature, so an override alone splits COMPOSED.md
into per-harness files (COMPOSED.<harness>.md).

Config schema (YAML):

    # Presence of this file activates agent-compose. Absent => no-op.
    # This machine's scope tags. Omit to compose every source (filtering off).
    scopes: [kai-public, work]
    # Explicit sources are composed first, in listed order.
    sources:
      - ~/projects/foo/AGENTS.COMPOSE.md
    # Roots are walked for AGENTS.COMPOSE.md files, appended in sorted order.
    # An out-of-repo root keeps host-local doctrine untracked yet composed.
    roots:
      - ~/projects/coilysiren
      - ~/projects/coilyco-flight-deck
      - ~/.config/agent-compose/sources
    # Optional load-point overrides. Defaults shown; opencode unset => skipped.
    load_points:
      claude: ~/.claude/CLAUDE.md
      codex: ~/.codex/AGENTS.md
      opencode: ~/.config/opencode/AGENTS.md

Usage:
    agent-compose            # compose + (re)point symlinks
    agent-compose --dry-run  # print what would happen, touch nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "agent-compose"
CONFIG_PATH = CONFIG_DIR / "agent-compose.yaml"
COMPOSED_PATH = CONFIG_DIR / "COMPOSED.md"

# qwen-opencode harness has its global load point at ~/.config/opencode/AGENTS.md
DEFAULT_LOAD_POINTS = {
    "claude": HOME / ".claude" / "CLAUDE.md",
    "codex": HOME / ".codex" / "AGENTS.md",
}

BANNER = "<!-- generated by agent-compose from agent-compose.yaml; do not edit -->"

# Disjoint source filename: always-global doctrine, never loaded by a harness's
# own AGENTS.md/CLAUDE.md cascade, only pulled in here.
SOURCE_FILENAME = "AGENTS.COMPOSE.md"


def _expand(path: str | Path) -> Path:
    return Path(path).expanduser()


def _normalize_scopes(value: object) -> list[str] | None:
    """Coerce a scopes value to a list of strings, or None when unset."""
    if value is None:
        return None
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [str(v) for v in value]
    return None


def _split_frontmatter(text: str) -> tuple[dict, str]:
    """Split a leading `--- ... ---` YAML frontmatter block from the body.

    Returns ({}, text) when there is no well-formed frontmatter fence.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            import yaml

            try:
                meta = yaml.safe_load("\n".join(lines[1:i])) or {}
            except yaml.YAMLError:
                meta = {}
            body = "\n".join(lines[i + 1 :])
            return (meta if isinstance(meta, dict) else {}), body
    return {}, text


def parse_source(path: Path) -> tuple[list[str] | None, str]:
    """Read a source: return its declared scopes and its frontmatter-stripped body.

    The scopes directive lives in YAML frontmatter and is removed from the body
    so it never reaches COMPOSED.md. Scopes are None when none are declared.
    """
    meta, body = _split_frontmatter(path.read_text(encoding="utf-8"))
    return _normalize_scopes(meta.get("scopes")), body


def source_harnesses(path: Path) -> list[str] | None:
    """Return a source's harness allowlist, or None when it applies to all."""
    meta, _ = _split_frontmatter(path.read_text(encoding="utf-8"))
    return _normalize_scopes(meta.get("harnesses"))


def discover_override(base: Path, harness: str) -> Path | None:
    """Return the per-harness section override sitting beside base, if any.

    An override is a sibling file named ``AGENTS.<harness>.md`` in the base's
    own directory. It declares no target path: the directory binds it, so an
    override can only patch the base source it lives next to and never reaches
    another repo or folder. The harness comes from the filename, so dropping a
    new override in place needs no config change.
    """
    candidate = base.parent / f"AGENTS.{harness}.md"
    return candidate if candidate.is_file() else None


def _header_level(line: str) -> int | None:
    """ATX heading level (1-6) for line, or None when it is not a heading."""
    match = re.match(r"(#{1,6}) +\S", line)
    return len(match.group(1)) if match else None


def _section_end(lines: list[str], start: int) -> int:
    """Index just past the section opened by the heading at lines[start].

    A section runs until the next heading of the same or shallower level, so a
    ``##`` section absorbs its ``###`` children.
    """
    level = _header_level(lines[start])
    assert level is not None
    end = start + 1
    while end < len(lines):
        here = _header_level(lines[end])
        if here is not None and here <= level:
            break
        end += 1
    return end


def _override_sections(body: str) -> list[tuple[str, list[str]]]:
    """Split an override body into (verbatim-heading, section-lines) pairs.

    Anything before the first heading is dropped: an override anchors by
    heading, so a preamble would have nothing to bind to.
    """
    lines = body.strip("\n").split("\n")
    start = 0
    while start < len(lines) and _header_level(lines[start]) is None:
        start += 1
    sections: list[tuple[str, list[str]]] = []
    while start < len(lines):
        end = _section_end(lines, start)
        sections.append((lines[start].rstrip(), lines[start:end]))
        start = end
    return sections


def apply_overrides(base_body: str, override_body: str) -> str:
    """Merge an override into a base body, keyed by verbatim heading line.

    A heading already present in the base replaces that whole section (heading
    through the next same-or-shallower heading). A heading absent from the base
    is appended, so an override may both rewrite and add sections. A heading
    that matches more than once raises RuntimeError, so an ambiguous anchor
    fails the compose loudly rather than patching the wrong section silently.
    Within a single source file headings are unique, which is exactly why the
    override binds to one directory's base.
    """
    lines = base_body.split("\n")
    for heading, section in _override_sections(override_body):
        matches = [i for i, line in enumerate(lines) if line.rstrip() == heading]
        if len(matches) > 1:
            raise RuntimeError(
                f"override heading {heading!r} matches {len(matches)} sections"
            )
        if matches:
            start = matches[0]
            lines[start : _section_end(lines, start)] = section
        else:
            if lines and lines[-1].strip():
                lines.append("")
            lines.extend(section)
    return "\n".join(lines)


# Trifecta navigation headings stripped from composed output: pure in-repo
# cross-links that mean nothing once read from ~/.config/agent-compose.
NAVIGATION_HEADINGS = {"see also"}

# A markdown inline-link tail ``(target)`` / ``(target "title")`` after a ``]``,
# capturing the target apart from any title so only the target is rewritten.
_LINK_RE = re.compile(r"(?<=\])\(([^)\s]+)(\s+[^)]*)?\)")


def _heading_text(line: str) -> str | None:
    """The text of an ATX heading line (hashes and surrounding space removed)."""
    if _header_level(line) is None:
        return None
    return line.lstrip("#").strip()


def strip_navigation_sections(body: str) -> str:
    """Drop repo-local navigation sections (e.g. ``## See also``) from a body.

    These trifecta cross-link sections address sibling files by repo-relative
    path and are meaningful only inside the source repo. A section runs from its
    heading to the next same-or-shallower heading, so it carries any trailing
    prose (the cross-reference line) out with it. Headings are matched by text
    against NAVIGATION_HEADINGS, case-insensitively.
    """
    lines = body.split("\n")
    kept: list[str] = []
    i = 0
    while i < len(lines):
        text = _heading_text(lines[i])
        if text is not None and text.casefold() in NAVIGATION_HEADINGS:
            i = _section_end(lines, i)
            continue
        kept.append(lines[i])
        i += 1
    return "\n".join(kept).strip("\n")


def _is_global_target(target: str) -> bool:
    """True when a link target already resolves without a source-repo cwd.

    URLs (any ``scheme://``), site-absolute paths, bare in-document anchors and
    ``mailto:`` targets need no rewrite; everything else is repo-relative.
    """
    return (
        target.startswith(("/", "#", "mailto:"))
        or re.match(r"[a-zA-Z][a-zA-Z0-9+.-]*://", target) is not None
    )


def absolutize_links(body: str, base_dir: Path) -> str:
    """Rewrite repo-relative markdown link targets to absolute paths.

    Composed output lives under ~/.config/agent-compose, so a source's
    repo-relative link (``](README.md)``) would dead-end there. Each relative
    target is resolved against base_dir (the source file's own directory) so the
    link stays followable from anywhere. Global targets (see _is_global_target)
    are left untouched, and a trailing ``#fragment`` on a relative path is kept.
    """

    def repl(match: re.Match[str]) -> str:
        target, title = match.group(1), match.group(2) or ""
        if _is_global_target(target):
            return match.group(0)
        path, sep, frag = target.partition("#")
        absolute = (base_dir / path).resolve()
        return f"({absolute}{sep}{frag}{title})"

    return _LINK_RE.sub(repl, body)


def select_by_scope(
    sources: list[Path], machine_scopes: list[str] | None
) -> list[Path]:
    """Keep sources whose declared scopes intersect the machine scopes.

    machine_scopes None (no `scopes` in config) turns filtering off: every
    source is kept. Under active filtering a source with no declared scopes is
    dropped, so an untagged file never leaks onto a scoped machine.
    """
    if machine_scopes is None:
        return list(sources)
    wanted = set(machine_scopes)
    return [
        path
        for path in sources
        if (scopes := parse_source(path)[0]) and wanted.intersection(scopes)
    ]


def select_by_harness(sources: list[Path], harness: str) -> list[Path]:
    """Keep sources shared globally or explicitly enabled for harness."""
    return [
        path
        for path in sources
        if (allowed := source_harnesses(path)) is None or harness in allowed
    ]


def harness_output_path(composed_path: Path, harness: str) -> Path:
    """Return the divergent output path for a harness beside composed_path."""
    return composed_path.with_name(
        f"{composed_path.stem}.{harness}{composed_path.suffix}"
    )


def plan_outputs(
    sources: list[Path], load_points: dict[str, Path], composed_path: Path
) -> tuple[
    dict[str, list[Path]],
    dict[str, dict[Path, Path]],
    dict[str, Path],
    list[str],
]:
    """Select each harness slice, its overrides, and shared/divergent outputs.

    A harness slice diverges when either its selected sources or its per-harness
    overrides differ from the others, so a section override alone is enough to
    split COMPOSED.md into per-harness files.
    """
    slices = {harness: select_by_harness(sources, harness) for harness in load_points}
    overrides = {
        harness: {
            src: override
            for src in selected
            if (override := discover_override(src, harness)) is not None
        }
        for harness, selected in slices.items()
    }
    errors = [
        f"no sources matched harness {harness!r}"
        for harness, selected in slices.items()
        if not selected
    ]
    signatures = {
        (
            tuple(slices[harness]),
            tuple(sorted((str(b), str(o)) for b, o in overrides[harness].items())),
        )
        for harness in load_points
    }
    if len(signatures) <= 1:
        outputs = {harness: composed_path for harness in load_points}
    else:
        outputs = {
            harness: harness_output_path(composed_path, harness)
            for harness in load_points
        }
    return slices, overrides, outputs, errors


def stale_generated_outputs(
    composed_path: Path, active_outputs: set[Path]
) -> list[Path]:
    """Find obsolete composer-owned outputs beside composed_path.

    Only files carrying the generated banner qualify, so similarly named user
    files are never removed.
    """
    candidates = [composed_path]
    candidates.extend(
        composed_path.parent.glob(f"{composed_path.stem}.*{composed_path.suffix}")
    )
    stale: list[Path] = []
    for path in candidates:
        if path in active_outputs or not path.is_file():
            continue
        try:
            with path.open(encoding="utf-8") as source:
                first_line = source.readline().rstrip("\n")
        except OSError:
            continue
        if first_line == BANNER:
            stale.append(path)
    return sorted(set(stale), key=str)


def discover_sources(root: Path) -> list[Path]:
    """Find AGENTS.COMPOSE.md files under root, sorted for deterministic output.

    Dot-directories (.git, vendored caches) are skipped so discovery never pulls
    in a stray copy from version-control or dependency trees.
    """
    found = [
        path
        for path in root.rglob(SOURCE_FILENAME)
        if not any(part.startswith(".") for part in path.relative_to(root).parts)
    ]
    return sorted(found, key=lambda p: str(p))


def gather_sources(config: dict) -> tuple[list[Path], list[str]]:
    """Resolve the full source list: explicit entries first, then discovered.

    Explicit `sources` keep their listed order; each declared `root` is walked
    and its AGENTS.COMPOSE.md files appended in sorted order. Duplicates (a file
    both listed and discovered) collapse to their first occurrence. Returns the
    sources and a list of error strings (missing files, non-directory roots).
    """
    errors: list[str] = []
    ordered: list[Path] = []
    seen: set[Path] = set()

    def add(path: Path) -> None:
        key = path.resolve()
        if key not in seen:
            seen.add(key)
            ordered.append(path)

    for raw in config.get("sources") or []:
        src = _expand(raw)
        if not src.is_file():
            errors.append(f"source not found: {src}")
            continue
        add(src)

    for raw in config.get("roots") or []:
        root = _expand(raw)
        if not root.is_dir():
            errors.append(f"root is not a directory: {root}")
            continue
        for src in discover_sources(root):
            add(src)

    return ordered, errors


def compose(sources: list[Path], overrides: dict[Path, Path] | None = None) -> str:
    """Concatenate source files into the composed-context body.

    Deterministic (no timestamps) so the drift check (#140) can reproduce it.
    Each section is fenced by a source-path comment for debuggability. When a
    source has a per-harness override, its sections are merged in before fencing
    and the fence records the override for provenance. Repo-local conventions
    are then rewritten for the composed context: ``## See also`` navigation is
    stripped and relative markdown links are absolutized against the source's
    own directory (#192).
    """
    overrides = overrides or {}
    parts = [BANNER]
    for src in sources:
        body = parse_source(src)[1].strip("\n")
        override = overrides.get(src)
        if override is not None:
            body = apply_overrides(body, parse_source(override)[1])
            fence = f"<!-- source: {src} (override: {override.name}) -->"
        else:
            fence = f"<!-- source: {src} -->"
        body = strip_navigation_sections(body)
        body = absolutize_links(body, src.parent)
        parts.append(f"{fence}\n{body}")
    return "\n\n".join(parts) + "\n"


def install_symlink(dst: Path, target: Path) -> str:
    """Point dst at target, backing up a pre-existing real file to dst.bak.

    Mirrors the shell role's ensure_link: an existing symlink is replaced, an existing
    regular file is moved aside, parents are created. Returns a log line.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    note = ""
    if dst.is_symlink():
        dst.unlink()
    elif dst.exists():
        backup = dst.with_name(dst.name + ".bak")
        dst.replace(backup)
        note = f" (backed up prior file to {backup})"
    dst.symlink_to(target)
    return f"linked  {dst} -> {target}{note}"


def load_config(config_path: Path) -> dict:
    """Parse the YAML config. Raises RuntimeError if PyYAML is unavailable."""
    try:
        import yaml
    except ModuleNotFoundError as exc:  # pragma: no cover - env-dependent
        raise RuntimeError("PyYAML not available") from exc
    data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise RuntimeError(f"{config_path}: top-level YAML must be a mapping")
    return data


def resolve_load_points(config: dict) -> dict[str, Path]:
    """Merge configured load-point overrides over the built-in defaults.

    A truthy value sets (or adds) a harness's load point. An explicit falsy
    value (`null` / `false`) opts a harness out, including a default one - so a
    Claude-only machine sets `codex: null` and a Codex-only machine sets
    `claude: null`. OpenCode stays opt-in: it is wired only when given a path.
    """
    points = dict(DEFAULT_LOAD_POINTS)
    overrides = config.get("load_points") or {}
    if isinstance(overrides, dict):
        for harness, value in overrides.items():
            if value:
                points[harness] = _expand(value)
            else:
                points.pop(harness, None)
    return points


def run(config_path: Path, composed_path: Path, *, dry_run: bool = False) -> int:
    """Compose and wire symlinks. No-op (return 0) when config is absent."""
    if not config_path.is_file():
        print(f"agent-compose: no config at {config_path}; nothing to do (opt-in)")
        return 0

    config = load_config(config_path)
    gathered, errors = gather_sources(config)
    if errors:
        for err in errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1

    machine_scopes = _normalize_scopes(config.get("scopes"))
    sources = select_by_scope(gathered, machine_scopes)
    excluded = len(gathered) - len(sources)
    if not sources:
        reason = (
            f"no sources matched this machine's scopes {machine_scopes}"
            if machine_scopes is not None
            else "no sources resolved (check `sources` / `roots`)"
        )
        sys.stderr.write(
            f"agent-compose: config present but {reason}; "
            "refusing to write an empty COMPOSED.md\n"
        )
        return 1

    load_points = resolve_load_points(config)
    slices, overrides, outputs, harness_errors = plan_outputs(
        sources, load_points, composed_path
    )
    if harness_errors:
        for err in harness_errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1
    tail = f" ({excluded} excluded by scope)" if excluded else ""

    planned: dict[Path, tuple[list[Path], dict[Path, Path]]] = {}
    for harness, target in outputs.items():
        planned[target] = (slices[harness], overrides[harness])
    if not load_points:
        planned[composed_path] = (sources, {})
    stale = stale_generated_outputs(composed_path, set(planned))

    if dry_run:
        for target, (selected, _ov) in sorted(
            planned.items(), key=lambda item: str(item[0])
        ):
            print(f"would write {target} ({len(selected)} source(s)){tail}")
        for target in stale:
            print(f"would remove {target} (obsolete generated output)")
        for harness, dst in sorted(load_points.items()):
            print(f"would link  {dst} -> {outputs[harness]}  [{harness}]")
        return 0

    composed_path.parent.mkdir(parents=True, exist_ok=True)
    for target in stale:
        target.unlink()
        print(f"removed {target} (obsolete generated output)")
    for target, (selected, override_map) in sorted(
        planned.items(), key=lambda item: str(item[0])
    ):
        target.write_text(compose(selected, override_map), encoding="utf-8")
        print(f"wrote   {target} ({len(selected)} source(s)){tail}")
    for harness, dst in sorted(load_points.items()):
        print(install_symlink(dst, outputs[harness]) + f"  [{harness}]")
    return 0


def check(config_path: Path, composed_path: Path) -> int:
    """Verify composed_path matches a fresh compose. Exit 1 on drift (#140).

    No-op (return 0) when no config is present, mirroring run()'s opt-in. On
    drift, prints a unified diff so the staleness is legible, then fails.
    """
    if not config_path.is_file():
        print(f"agent-compose: no config at {config_path}; nothing to check (opt-in)")
        return 0

    config = load_config(config_path)
    gathered, errors = gather_sources(config)
    if errors:
        for err in errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1
    sources = select_by_scope(gathered, _normalize_scopes(config.get("scopes")))
    if not sources:
        sys.stderr.write("agent-compose: no sources resolved; cannot check drift\n")
        return 1

    load_points = resolve_load_points(config)
    slices, overrides, outputs, harness_errors = plan_outputs(
        sources, load_points, composed_path
    )
    if harness_errors:
        for err in harness_errors:
            sys.stderr.write(f"agent-compose: {err}\n")
        return 1

    planned: dict[Path, tuple[list[Path], dict[Path, Path]]] = {}
    for harness, target in outputs.items():
        planned[target] = (slices[harness], overrides[harness])
    if not load_points:
        planned[composed_path] = (sources, {})
    stale = stale_generated_outputs(composed_path, set(planned))

    import difflib

    drifted = False
    for target in stale:
        drifted = True
        sys.stderr.write(
            f"agent-compose: drift - obsolete generated output remains at {target}. "
            "Run `agent-compose` to remove it.\n"
        )
    for target, (selected, override_map) in sorted(
        planned.items(), key=lambda item: str(item[0])
    ):
        expected = compose(selected, override_map)
        actual = target.read_text(encoding="utf-8") if target.exists() else ""
        if actual == expected:
            print(f"agent-compose: {target} in sync")
            continue
        drifted = True
        sys.stderr.write(
            f"agent-compose: drift - {target} is missing, stale, or hand-edited. "
            "Run `agent-compose` to regenerate.\n"
        )
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"{target} (on disk)",
            tofile="expected (fresh compose)",
            lineterm="",
        )
        for line in list(diff)[:40]:
            sys.stderr.write(line + "\n")
    return 1 if drifted else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--dry-run", action="store_true", help="print the plan, change nothing"
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="verify COMPOSED.md is in sync with the sources; exit 1 on drift",
    )
    args = parser.parse_args()
    try:
        if args.check:
            return check(CONFIG_PATH, COMPOSED_PATH)
        return run(CONFIG_PATH, COMPOSED_PATH, dry_run=args.dry_run)
    except RuntimeError as exc:
        sys.stderr.write(f"agent-compose: {exc}\n")
        return 1


def check_main() -> int:
    """Console entry for the drift pre-commit hook (check-agent-compose-drift)."""
    try:
        return check(CONFIG_PATH, COMPOSED_PATH)
    except RuntimeError as exc:
        sys.stderr.write(f"agent-compose: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
