#!/usr/bin/env python3
"""Generate the role context measurement inventory.

The checked-in role YAML snapshots are the measurement evidence. This generator
validates one snapshot per AOS launch-profile role and keeps the aggregate report
drift-proof with ``--check``.

See docs/context-budget-role.md.
"""
from __future__ import annotations

import argparse
import difflib
import sys
import textwrap
from collections.abc import Iterable, Mapping
from pathlib import Path

import yaml

from agentic_os.context_budget_role import load_snapshot

_REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = _REPO_ROOT / "docs"
ROLE_SCOPE_PATH = _REPO_ROOT / ".agents" / "harness-launch-profiles.yaml"
GENERATED_MARKER = (
    "<!-- GENERATED by generate-context-budget-role-reports - "
    "do not hand-edit. -->"
)
GENERATED_HEADER = (
    f"{GENERATED_MARKER}\n"
    "<!-- Regenerate: ward exec gen-context-budget-role-reports. -->\n"
)


def _mapping(value: object, label: str) -> Mapping[str, object]:
    if not isinstance(value, dict):
        raise RuntimeError(f"{label} must be a mapping")
    return value


def load_canonical_roles(path: Path = ROLE_SCOPE_PATH) -> tuple[str, ...]:
    """Load the ordered role ids from AOS's launch-profile configuration."""
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise RuntimeError(f"read launch profiles {path}: {exc}") from exc
    if not isinstance(document, dict) or not isinstance(document.get("roles"), dict):
        raise RuntimeError(f"{path}: launch profiles must contain a roles mapping")
    roles = tuple(document["roles"])
    if not roles or not all(isinstance(role, str) and role for role in roles):
        raise RuntimeError(f"{path}: launch-profile roles are malformed")
    return roles


def _snapshot_identity(path: Path, roles: Iterable[str]) -> str:
    for role in roles:
        if path.name == f"context-budget-{role}-current.yaml":
            return role
    raise RuntimeError(f"{path}: current snapshot filename has no canonical AOS role")


def load_role_snapshots(
    docs_dir: Path,
    roles: Iterable[str],
) -> dict[str, dict[str, object]]:
    """Load and validate exactly one current snapshot per role."""
    role_order = tuple(roles)
    snapshots: dict[str, dict[str, object]] = {}
    for path in sorted(docs_dir.glob("context-budget-*-current.yaml")):
        role = _snapshot_identity(path, role_order)
        snapshot = load_snapshot(path)
        subject = _mapping(snapshot.get("subject"), f"{path}: subject")
        if subject != {"role": role}:
            raise RuntimeError(f"{path}: snapshot subject does not match its filename")
        if role in snapshots:
            raise RuntimeError(f"{path}: duplicate snapshot for {role}")
        snapshots[role] = snapshot
    missing = [role for role in role_order if role not in snapshots]
    if missing:
        raise RuntimeError(f"roles have no current snapshot: {', '.join(missing)}")
    return snapshots


def _nested_int(snapshot: Mapping[str, object], *keys: str) -> int:
    value: object = snapshot
    for key in keys:
        value = _mapping(value, ".".join(keys)).get(key)
    if not isinstance(value, int):
        raise RuntimeError(f"snapshot {'.'.join(keys)} must be an integer")
    return value


def _composed_count(snapshot: Mapping[str, object]) -> int:
    eager = _mapping(
        _mapping(snapshot.get("breakdown"), "snapshot breakdown").get("eager"),
        "snapshot eager breakdown",
    )
    composed = eager.get("role-composed-frontmatter")
    if composed is None:
        return 0
    return _nested_int({"value": composed}, "value", "components")


def _role_label(role: str) -> str:
    labels = {
        "qa": "QA",
        "strats": "Portfolio Strategist",
        "content": "Content Manager",
        "ai": "AI Engineer",
    }
    return labels.get(role, role.replace("-", " ").title())


def _wrapped_lines(text: str, *, subsequent_indent: str = "") -> list[str]:
    return textwrap.wrap(
        text,
        width=88,
        subsequent_indent=subsequent_indent,
        break_long_words=False,
        break_on_hyphens=False,
    )


def render_inventory(
    roles: Iterable[str],
    snapshots: Mapping[str, dict[str, object]],
) -> str:
    """Render the cross-role measurement inventory."""
    role_order = tuple(roles)
    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "",
        "# Current role context inventory",
        "",
    ]
    lines.extend(
        _wrapped_lines(
            f"The {len(role_order)} AOS launch-profile roles each have one "
            "harness-neutral snapshot. Every snapshot is validated before its "
            "measurements enter this report."
        )
    )
    lines.extend(["", "## Roles", ""])
    for role in role_order:
        snapshot = snapshots[role]
        eager = _nested_int(snapshot, "totals", "eager", "tokens")
        lazy = _nested_int(snapshot, "totals", "lazy", "tokens")
        composed = _composed_count(snapshot)
        lines.extend(
            _wrapped_lines(
                f"* [{_role_label(role)}](context-budget-{role}-current.yaml) - "
                f"eager {eager:,}, lazy {lazy:,}, composed {composed}.",
                subsequent_indent="  ",
            )
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
        ]
    )
    lines.extend(
        _wrapped_lines(
            "Snapshots stop at the complete Agent Compose role bundle. They do not "
            "select a harness, projection layout, model family, or context window."
        )
    )
    lines.extend(
        [
            "",
            "## See also",
            "",
            "* [Role snapshot contract](context-budget-role.md) - capture, comparison,",
            "  and failure rules.",
            "* [Context measurement report](context-budget.md) - component definitions",
            "  and token proxy.",
        ]
    )
    return "\n".join(lines) + "\n"


def build_reports(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
) -> dict[Path, str]:
    """Build the expected report without mutating the filesystem."""
    role_order = tuple(roles) if roles is not None else load_canonical_roles()
    snapshots = load_role_snapshots(docs_dir, role_order)
    return {
        docs_dir / "context-budget-role-current.md": render_inventory(
            role_order,
            snapshots,
        )
    }


def _stale_generated_reports(docs_dir: Path, expected: set[Path]) -> list[Path]:
    stale: list[Path] = []
    for path in docs_dir.glob("context-budget-role*-current.md"):
        if path in expected or not path.is_file():
            continue
        if path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            stale.append(path)
    return sorted(stale)


def generate(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
) -> int:
    reports = build_reports(docs_dir, roles)
    for path, content in reports.items():
        path.write_text(content, encoding="utf-8")
    for path in _stale_generated_reports(docs_dir, set(reports)):
        path.unlink()
    print(f"context-budget-role-reports: wrote {len(reports)} inventory document")
    return 0


def check_drift(
    docs_dir: Path = DOCS_DIR,
    roles: Iterable[str] | None = None,
) -> int:
    reports = build_reports(docs_dir, roles)
    stale = _stale_generated_reports(docs_dir, set(reports))
    drifted = [
        (path, content, path.read_text(encoding="utf-8") if path.exists() else "")
        for path, content in reports.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if not drifted and not stale:
        print(f"context-budget-role-reports: {len(reports)} inventory document in sync")
        return 0
    for path in stale:
        sys.stderr.write(f"context-budget-role-reports: stale generated report {path.name}\n")
    for path, expected, actual in drifted:
        sys.stderr.write(
            f"context-budget-role-reports: {path.name} is missing, stale, or "
            "hand-edited\n"
        )
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=f"{path.name} (on disk)",
            tofile="expected (fresh generate)",
            lineterm="",
        )
        for line in list(diff)[:24]:
            sys.stderr.write(line + "\n")
    sys.stderr.write(
        "Run `ward exec gen-context-budget-role-reports` to regenerate.\n"
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated role report matches the current YAML snapshots",
    )
    parser.add_argument(
        "--docs",
        type=Path,
        default=DOCS_DIR,
        help="directory containing the snapshots and generated report",
    )
    args = parser.parse_args()
    try:
        return check_drift(args.docs) if args.check else generate(args.docs)
    except RuntimeError as exc:
        sys.stderr.write(f"context-budget-role-reports: {exc}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
