package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/urfave/cli/v3"
)

const (
	bundlesCommand         = "bundles"
	bundlesFormat          = "aterm.bundles.v1"
	bundleIdentifierPrefix = "me.coilysiren.aterm"
	bundleNamePrefix       = "aterm "
	bundleIconName         = "aterm"
	bundleMarker           = "# generated by `aterm bundles`"
	bundleDirMode          = 0o755
	bundleFileMode         = 0o644
	bundleExecMode         = 0o755
)

type bundleSpec struct {
	Role             string
	DisplayName      string
	Person           string
	Version          string
	Icon             bool
	WorkingDirectory string
	ATermBin         string
	AOSBin           string
	AgentComposeBin  string
	TerminalBin      string
}

func (s bundleSpec) name() string { return bundleNamePrefix + s.Role }

func (s bundleSpec) identifier() string { return bundleIdentifierPrefix + "." + s.Role }

type bundleItem struct {
	Role       string `json:"role"`
	Person     string `json:"person"`
	Identifier string `json:"identifier"`
	Path       string `json:"path"`
	Executable string `json:"executable"`
	Launcher   string `json:"launcher"`
	Plist      string `json:"plist"`
}

type bundlePlan struct {
	Format string       `json:"format"`
	Output string       `json:"output"`
	Icon   string       `json:"icon"`
	Items  []bundleItem `json:"items"`
	Stale  []string     `json:"stale"`
}

func newBundlesCommand(deps commandDeps) *cli.Command {
	return &cli.Command{
		Name:  bundlesCommand,
		Usage: "write one macOS .app launcher per live role",
		Description: "Every live role becomes a launchable, Spotlight-searchable app that opens\n" +
			"the same window `aterm <role>` opens. The wrapper bakes in the binaries it\n" +
			"resolved, because a Finder launch carries none of your shell's PATH.",
		Flags: append(bundleBinaryFlags(), []cli.Flag{
			&cli.StringFlag{
				Name:  "output-dir",
				Value: defaultBundleDir(),
				Usage: "directory to write the bundles into",
			},
			&cli.StringFlag{
				Name:  "icon",
				Usage: "shared .icns for every bundle (macOS draws its generic app icon without one)",
			},
			&cli.StringFlag{
				Name:  "working-directory",
				Value: defaultWorkingDirectory(),
				Usage: "agent working directory baked into every bundle",
			},
			&cli.BoolFlag{
				Name:  "dry-run",
				Usage: "show what would be written, and write nothing",
			},
			&cli.BoolFlag{
				Name:  "json",
				Usage: "with --dry-run, the machine plan instead of the rendered one",
			},
		}...),
		Action: func(ctx context.Context, cmd *cli.Command) error {
			return runBundles(ctx, deps, cmd)
		},
	}
}

// bundleBinaryFlags rebuilds the root's binary flags rather than sharing them,
// so `aterm bundles --aos-bin ...` parses without depending on flag persistence.
func bundleBinaryFlags() []cli.Flag {
	return []cli.Flag{
		&cli.StringFlag{
			Name:    "aterm-bin",
			Value:   defaultATermBin,
			Usage:   "installed aterm the bundles call, resolved and baked in",
			Sources: cli.EnvVars("ATERM_BIN"),
		},
		&cli.StringFlag{
			Name:    "agent-compose-bin",
			Value:   defaultOverlayBin,
			Sources: cli.EnvVars("AGENT_COMPOSE_BIN"),
		},
		&cli.StringFlag{
			Name:    "aos-bin",
			Value:   defaultAOSBin,
			Sources: cli.EnvVars("AOS_BIN"),
		},
		&cli.StringFlag{
			Name:    "terminal-bin",
			Value:   defaultTerminalBin,
			Usage:   "terminal the bundles open",
			Sources: cli.EnvVars("ATERM_TERMINAL_BIN", "KITTY_BIN"),
		},
	}
}

func defaultBundleDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "."
	}
	return filepath.Join(home, "Applications")
}

func runBundles(ctx context.Context, deps commandDeps, cmd *cli.Command) error {
	if runtime.GOOS != "darwin" {
		return withExit(exitUsage, fmt.Errorf(
			"bundles writes macOS .app launchers, and this host is %s", runtime.GOOS))
	}
	plan, err := buildBundlePlan(ctx, deps, cmd)
	if err != nil {
		return err
	}
	stdout := cmd.Root().Writer
	if cmd.Bool("json") && !cmd.Bool("dry-run") {
		return withExit(exitUsage, fmt.Errorf("--json applies to --dry-run"))
	}
	if cmd.Bool("dry-run") {
		if cmd.Bool("json") {
			encoded, err := json.MarshalIndent(plan, "", "  ")
			if err != nil {
				return fmt.Errorf("marshal the bundle plan: %w", err)
			}
			_, err = fmt.Fprintf(stdout, "%s\n", encoded)
			return err
		}
		return renderBundlePlan(stdout, plan)
	}
	if err := os.MkdirAll(plan.Output, bundleDirMode); err != nil {
		return fmt.Errorf("create %q: %w", plan.Output, err)
	}
	// Every target is cleared before any is written, so a refusal partway down
	// the roster cannot leave half a Dock folder regenerated.
	for _, item := range plan.Items {
		if err := replaceable(item.Path); err != nil {
			return err
		}
	}
	for _, item := range plan.Items {
		if err := writeBundle(item, plan.Icon); err != nil {
			return err
		}
	}
	return announceBundles(stdout, plan)
}

func buildBundlePlan(ctx context.Context, deps commandDeps, cmd *cli.Command) (bundlePlan, error) {
	agentCompose, err := requireBinary(deps.lookPath, cmd.String("agent-compose-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("agent-compose binary: %w", err)
	}
	roster, err := loadRoster(ctx, deps, agentCompose)
	if err != nil {
		return bundlePlan{}, err
	}
	aos, err := requireBinary(deps.lookPath, cmd.String("aos-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("aos binary: %w", err)
	}
	terminal, err := requireBinary(deps.lookPath, cmd.String("terminal-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("terminal binary: %w", err)
	}
	launcher, err := requireBinary(deps.lookPath, cmd.String("aterm-bin"))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("aterm binary: %w", err)
	}
	cwd, err := validateWorkingDirectory(cmd.String("working-directory"))
	if err != nil {
		return bundlePlan{}, err
	}
	output, err := filepath.Abs(strings.TrimSpace(cmd.String("output-dir")))
	if err != nil {
		return bundlePlan{}, fmt.Errorf("resolve the output directory: %w", err)
	}
	icon, err := resolveIcon(cmd.String("icon"))
	if err != nil {
		return bundlePlan{}, err
	}
	plan := bundlePlan{Format: bundlesFormat, Output: output, Icon: icon}
	for _, role := range roster.Items {
		if len(role.nativeSeats()) == 0 {
			continue
		}
		spec := bundleSpec{
			Role:             role.Slug,
			DisplayName:      role.DisplayName,
			Person:           role.Identity.Name,
			Version:          version,
			Icon:             icon != "",
			WorkingDirectory: cwd,
			ATermBin:         launcher,
			AOSBin:           aos,
			AgentComposeBin:  agentCompose,
			TerminalBin:      terminal,
		}
		plan.Items = append(plan.Items, bundleItem{
			Role:       spec.Role,
			Person:     spec.Person,
			Identifier: spec.identifier(),
			Path:       filepath.Join(output, spec.name()+".app"),
			Executable: spec.name(),
			Launcher:   bundleLauncher(spec),
			Plist:      bundleInfoPlist(spec),
		})
	}
	if len(plan.Items) == 0 {
		return bundlePlan{}, withExit(exitOffRoster,
			fmt.Errorf("no live role has a launchable native seat"))
	}
	plan.Stale = staleBundles(output, roster)
	return plan, nil
}

func resolveIcon(value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", nil
	}
	absolute, err := filepath.Abs(value)
	if err != nil {
		return "", fmt.Errorf("resolve the icon: %w", err)
	}
	info, err := os.Stat(absolute)
	if err != nil {
		return "", fmt.Errorf("inspect the icon %q: %w", absolute, err)
	}
	if info.IsDir() {
		return "", fmt.Errorf("icon %q is a directory", absolute)
	}
	return absolute, nil
}

// staleBundles names bundles this command wrote for a role that has since left
// the roster. It deletes nothing, because removing an app is the caller's call.
func staleBundles(output string, roster rosterDocument) []string {
	entries, err := os.ReadDir(output)
	if err != nil {
		return nil
	}
	stale := make([]string, 0)
	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasPrefix(name, bundleNamePrefix) || !strings.HasSuffix(name, ".app") {
			continue
		}
		slug := strings.TrimSuffix(strings.TrimPrefix(name, bundleNamePrefix), ".app")
		if _, live := roster.role(slug); live {
			continue
		}
		path := filepath.Join(output, name)
		if generatedBundle(path, bundleNamePrefix+slug) {
			stale = append(stale, path)
		}
	}
	if len(stale) == 0 {
		return nil
	}
	return stale
}

func generatedBundle(root, executable string) bool {
	raw, err := os.ReadFile(filepath.Join(root, "Contents", "MacOS", executable))
	if err != nil {
		return false
	}
	return strings.Contains(string(raw), bundleMarker)
}

func writeBundle(item bundleItem, icon string) error {
	if err := os.RemoveAll(item.Path); err != nil {
		return fmt.Errorf("clear %q: %w", item.Path, err)
	}
	contents := filepath.Join(item.Path, "Contents")
	executable := filepath.Join(contents, "MacOS", item.Executable)
	if err := os.MkdirAll(filepath.Dir(executable), bundleDirMode); err != nil {
		return fmt.Errorf("create %q: %w", filepath.Dir(executable), err)
	}
	if err := os.WriteFile(executable, []byte(item.Launcher), bundleExecMode); err != nil {
		return fmt.Errorf("write %q: %w", executable, err)
	}
	plist := filepath.Join(contents, "Info.plist")
	if err := os.WriteFile(plist, []byte(item.Plist), bundleFileMode); err != nil {
		return fmt.Errorf("write %q: %w", plist, err)
	}
	pkgInfo := filepath.Join(contents, "PkgInfo")
	if err := os.WriteFile(pkgInfo, []byte("APPL????"), bundleFileMode); err != nil {
		return fmt.Errorf("write %q: %w", pkgInfo, err)
	}
	if icon == "" {
		return nil
	}
	return copyIcon(icon, filepath.Join(contents, "Resources", bundleIconName+".icns"))
}

// replaceable refuses to overwrite anything this command did not write, so a
// mistyped output directory cannot delete an app that happens to share a name.
func replaceable(root string) error {
	if _, err := os.Stat(root); os.IsNotExist(err) {
		return nil
	}
	name := strings.TrimSuffix(filepath.Base(root), ".app")
	if generatedBundle(root, name) {
		return nil
	}
	return fmt.Errorf("%q exists and was not written by `aterm bundles`, so it stays untouched", root)
}

func copyIcon(source, destination string) error {
	if err := os.MkdirAll(filepath.Dir(destination), bundleDirMode); err != nil {
		return fmt.Errorf("create %q: %w", filepath.Dir(destination), err)
	}
	raw, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("read the icon %q: %w", source, err)
	}
	if err := os.WriteFile(destination, raw, bundleFileMode); err != nil {
		return fmt.Errorf("write %q: %w", destination, err)
	}
	return nil
}

func announceBundles(writer io.Writer, plan bundlePlan) error {
	for _, item := range plan.Items {
		if _, err := fmt.Fprintf(writer, "%s // %s\n", item.Path, item.Person); err != nil {
			return err
		}
	}
	for _, path := range plan.Stale {
		if _, err := fmt.Fprintf(writer, "stale, no longer a live role: %s\n", path); err != nil {
			return err
		}
	}
	return nil
}
