#!/usr/bin/env python3
"""pre-commit hook: assert AGENTS.md carries the managed git-workflow block.

The block under `## Agent rules` in every root `AGENTS.md` is fully generated by
`agentic_os.generators.generate_git_workflow` from the lane the same file
declares as `ward.workflow`. It must never be hand-edited. This hook regenerates
the expected block offline and fails on any drift, a missing block, a block that
no longer matches the declared lane, or a legacy one-line stamp left beside it.

Unlike the workspace-pointer hook, this one is org-agnostic and exempts no base
repo: a landing lane binds an agent in the canonical base exactly as it binds
one in a consumer. It no-ops, fail-open, only where the block cannot apply - a
repo with no root AGENTS.md, a symlinked AGENTS.md (the cross-harness sharing
mechanism), or an explicit `enabled = false` opt-out.

Schema and rollout: see docs/features-agents.md.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import NoReturn

from agentic_os.config import is_enabled
from agentic_os.generators.generate_git_workflow import check_drift

HOOK_ID = "git-workflow"
TRACKER = "docs/features-agents.md"

REGEN_HINT = "  regenerate: python3 scripts/apply-git-workflow.py --repo <name>"


def fail(msgs: list[str]) -> NoReturn:
    for m in msgs:
        print(f"check-{HOOK_ID}: {m}", file=sys.stderr)
    print(REGEN_HINT, file=sys.stderr)
    print(f"  see {TRACKER} for schema", file=sys.stderr)
    sys.exit(1)


def main() -> int:
    if not is_enabled(HOOK_ID):
        print(f"{HOOK_ID}: disabled by repo config")
        return 0

    agents = Path.cwd() / "AGENTS.md"
    if not agents.exists() or agents.is_symlink():
        return 0

    problems = check_drift(agents.read_text(encoding="utf-8", errors="replace"))
    if problems:
        fail(problems)
    print(f"{HOOK_ID} check: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
