#!/usr/bin/env bash
# Regenerate the committed ward-kdl ops reference dump.
#
# Renders `ward ops forgejo describe` (the full operator-verb surface routed
# through the ward-kdl guardfile runtime) into docs/ward-ops-forgejo-reference.md
# with a provenance header. The committed render is the off-disk, greppable
# answer to "what is the operator-verb name" so a cold agent never has to guess
# or run the binary. Regenerate at converge time, or whenever ward-kdl's forgejo
# surface changes. See agentic-os#261.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
out="$repo_root/docs/ward-ops-forgejo-reference.md"
as_of="$(date -u +%Y-%m-%d)"
ward_version="$(ward --version 2>/dev/null | head -1 | sed 's/^ward version //' || echo "unknown")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "<!-- GENERATED by scripts/gen-ward-ops-reference.sh - do not hand-edit. -->"
  echo "<!-- Regenerate: ward exec gen-ward-ops-reference -->"
  echo ""
  echo "# ward ops forgejo - committed reference"
  echo ""
  echo "**as-of:** $as_of - **source:** \`ward ops forgejo describe\` ($ward_version) - **regenerate:** \`ward exec gen-ward-ops-reference\`"
  echo ""
  echo "Operator verbs live in **ward-kdl**, surfaced as \`ward ops <area> ...\`. This is a"
  echo "committed render of \`ward ops forgejo describe\` so the verb names survive off-disk"
  echo "and stay greppable without running the binary. The live binary is the source of"
  echo "truth - if this file looks stale, run \`ward ops forgejo describe\` (or \`--help\`) and"
  echo "regenerate. Never guess an operator-verb name from prior. The deprecated \`coily ops\`"
  echo "spelling is gone (agentic-os#261)."
  echo ""
  echo "---"
  echo ""
  ward ops forgejo describe
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "wrote $out (as-of $as_of, $ward_version)"
